/* This is generated code, don't alter */
enum IfcDerivedUnitEnum {
  ACCELERATIONUNIT = 0,
  ANGULARVELOCITYUNIT = 1,
  AREADENSITYUNIT = 2,
  COMPOUNDPLANEANGLEUNIT = 3,
  CURVATUREUNIT = 4,
  DYNAMICVISCOSITYUNIT = 5,
  HEATFLUXDENSITYUNIT = 6,
  HEATINGVALUEUNIT = 7,
  INTEGERCOUNTRATEUNIT = 8,
  IONCONCENTRATIONUNIT = 9,
  ISOTHERMALMOISTURECAPACITYUNIT = 10,
  KINEMATICVISCOSITYUNIT = 11,
  LINEARFORCEUNIT = 12,
  LINEARMOMENTUNIT = 13,
  LINEARSTIFFNESSUNIT = 14,
  LINEARVELOCITYUNIT = 15,
  LUMINOUSINTENSITYDISTRIBUTIONUNIT = 16,
  MASSDENSITYUNIT = 17,
  MASSFLOWRATEUNIT = 18,
  MASSPERLENGTHUNIT = 19,
  MODULUSOFELASTICITYUNIT = 20,
  MODULUSOFLINEARSUBGRADEREACTIONUNIT = 21,
  MODULUSOFROTATIONALSUBGRADEREACTIONUNIT = 22,
  MODULUSOFSUBGRADEREACTIONUNIT = 23,
  MOISTUREDIFFUSIVITYUNIT = 24,
  MOLECULARWEIGHTUNIT = 25,
  MOMENTOFINERTIAUNIT = 26,
  PHUNIT = 27,
  PLANARFORCEUNIT = 28,
  ROTATIONALFREQUENCYUNIT = 29,
  ROTATIONALMASSUNIT = 30,
  ROTATIONALSTIFFNESSUNIT = 31,
  SECTIONAREAINTEGRALUNIT = 32,
  SECTIONMODULUSUNIT = 33,
  SHEARMODULUSUNIT = 34,
  SOUNDPOWERLEVELUNIT = 35,
  SOUNDPOWERUNIT = 36,
  SOUNDPRESSURELEVELUNIT = 37,
  SOUNDPRESSUREUNIT = 38,
  SPECIFICHEATCAPACITYUNIT = 39,
  TEMPERATUREGRADIENTUNIT = 40,
  TEMPERATURERATEOFCHANGEUNIT = 41,
  THERMALADMITTANCEUNIT = 42,
  THERMALCONDUCTANCEUNIT = 43,
  THERMALEXPANSIONCOEFFICIENTUNIT = 44,
  THERMALRESISTANCEUNIT = 45,
  THERMALTRANSMITTANCEUNIT = 46,
  TORQUEUNIT = 47,
  VAPORPERMEABILITYUNIT = 48,
  VOLUMETRICFLOWRATEUNIT = 49,
  WARPINGCONSTANTUNIT = 50,
  WARPINGMOMENTUNIT = 51,
  USERDEFINED = 52,
}

const IfcDerivedUnitEnumCount = 53

export { IfcDerivedUnitEnum, IfcDerivedUnitEnumCount }

/* This is generated code, don't alter */
import MinimalPerfectHash from '../../indexing/minimal_perfect_hash'

let gMapIfcDerivedUnitEnum =
  new Int32Array( [7,27,217,96,2,336,1,-19,-34,323,629,43,5] )

let prefixSumAddressIfcDerivedUnitEnum =
  new Uint32Array( [0,25,44,66,84,109,130,148,172,201,222,239,261,283,307,338,357,382,394,417,438,459,483,501,514,537,560,585,604,621,645,671,696,716,733,748,789,814,832,869,902,918,935,970,1002,1023,1043,1063,1084,1110,1134,1155,1163,1181] )

let slotMapIfcDerivedUnitEnum =
  new Int32Array( [32,38,9,13,31,35,34,49,41,25,17,5,8,3,23,51,40,47,48,26,14,37,7,52,42,45,20,19,28,11,46,29,15,2,4,22,24,0,21,44,36,12,16,10,6,30,33,50,39,43,1,27,18] )

let encodedDataIfcDerivedUnitEnum =
  (new TextEncoder()).encode( ".SECTIONAREAINTEGRALUNIT..SOUNDPRESSUREUNIT..IONCONCENTRATIONUNIT..LINEARMOMENTUNIT..ROTATIONALSTIFFNESSUNIT..SOUNDPOWERLEVELUNIT..SHEARMODULUSUNIT..VOLUMETRICFLOWRATEUNIT..TEMPERATURERATEOFCHANGEUNIT..MOLECULARWEIGHTUNIT..MASSDENSITYUNIT..DYNAMICVISCOSITYUNIT..INTEGERCOUNTRATEUNIT..COMPOUNDPLANEANGLEUNIT..MODULUSOFSUBGRADEREACTIONUNIT..WARPINGMOMENTUNIT..TEMPERATUREGRADIENTUNIT..TORQUEUNIT..VAPORPERMEABILITYUNIT..MOMENTOFINERTIAUNIT..LINEARSTIFFNESSUNIT..SOUNDPRESSURELEVELUNIT..HEATINGVALUEUNIT..USERDEFINED..THERMALADMITTANCEUNIT..THERMALRESISTANCEUNIT..MODULUSOFELASTICITYUNIT..MASSPERLENGTHUNIT..PLANARFORCEUNIT..KINEMATICVISCOSITYUNIT..THERMALTRANSMITTANCEUNIT..ROTATIONALFREQUENCYUNIT..LINEARVELOCITYUNIT..AREADENSITYUNIT..CURVATUREUNIT..MODULUSOFROTATIONALSUBGRADEREACTIONUNIT..MOISTUREDIFFUSIVITYUNIT..ACCELERATIONUNIT..MODULUSOFLINEARSUBGRADEREACTIONUNIT..THERMALEXPANSIONCOEFFICIENTUNIT..SOUNDPOWERUNIT..LINEARFORCEUNIT..LUMINOUSINTENSITYDISTRIBUTIONUNIT..ISOTHERMALMOISTURECAPACITYUNIT..HEATFLUXDENSITYUNIT..ROTATIONALMASSUNIT..SECTIONMODULUSUNIT..WARPINGCONSTANTUNIT..SPECIFICHEATCAPACITYUNIT..THERMALCONDUCTANCEUNIT..ANGULARVELOCITYUNIT..PHUNIT..MASSFLOWRATEUNIT." )

let IfcDerivedUnitEnumSearch =
  new MinimalPerfectHash< IfcDerivedUnitEnum >( gMapIfcDerivedUnitEnum, prefixSumAddressIfcDerivedUnitEnum, slotMapIfcDerivedUnitEnum, encodedDataIfcDerivedUnitEnum )

export { IfcDerivedUnitEnumSearch }


/* This is generated cold, don't alter */
import StepEnumParser from '../../step/parsing/step_enum_parser'

const parser = StepEnumParser.Instance

export function IfcDerivedUnitEnumDeserializeStep(
  input: Uint8Array,
  cursor: number,
  endCursor: number ): IfcDerivedUnitEnum | undefined {
  return parser.extract< IfcDerivedUnitEnum >( IfcDerivedUnitEnumSearch, input, cursor, endCursor )
}
