
import { IfcRepresentationItem } from "./index"

/* This is generated code, don't modify */
import EntityTypesIfc4x3 from './entity_types_ifc4x3.gen'
import StepEntityInternalReference from '../../step/step_entity_internal_reference'
import StepEntityBase from '../../step/step_entity_base'
import StepModelBase from '../../step/step_model_base'

///**
// *  */
export abstract class IfcGeometricRepresentationItem extends IfcRepresentationItem {
  public get type(): EntityTypesIfc4x3 {
    return EntityTypesIfc4x3.IFCGEOMETRICREPRESENTATIONITEM
  }


  constructor(
    localID: number,
    internalReference: StepEntityInternalReference< EntityTypesIfc4x3 >,
    model: StepModelBase< EntityTypesIfc4x3, StepEntityBase< EntityTypesIfc4x3 > >,
    multiReference?: StepEntityInternalReference< EntityTypesIfc4x3 >[] ) {

    super( localID, internalReference, model, multiReference )

    if ( multiReference !== void 0 ) {

      const localReference =
        multiReference.find( ( item ) => item.typeID === IfcGeometricRepresentationItem.expectedType )

      if ( localReference === void 0 ) {
        throw new Error( "Couldn't find multi-element reference for IfcGeometricRepresentationItem" )
      }

      this.multiReference_ ??= []

      this.multiReference_.push( localReference )

      localReference.visitedMulti = true
    }
  }

  public static readonly query = 
    [ EntityTypesIfc4x3.IFCANNOTATIONFILLAREA, EntityTypesIfc4x3.IFCBOOLEANRESULT, EntityTypesIfc4x3.IFCBOUNDINGBOX, EntityTypesIfc4x3.IFCDIRECTION, EntityTypesIfc4x3.IFCFACEBASEDSURFACEMODEL, EntityTypesIfc4x3.IFCFILLAREASTYLEHATCHING, EntityTypesIfc4x3.IFCFILLAREASTYLETILES, EntityTypesIfc4x3.IFCGEOMETRICSET, EntityTypesIfc4x3.IFCHALFSPACESOLID, EntityTypesIfc4x3.IFCPLANAREXTENT, EntityTypesIfc4x3.IFCSECTIONEDSPINE, EntityTypesIfc4x3.IFCSHELLBASEDSURFACEMODEL, EntityTypesIfc4x3.IFCTEXTLITERAL, EntityTypesIfc4x3.IFCVECTOR, EntityTypesIfc4x3.IFCBOOLEANCLIPPINGRESULT, EntityTypesIfc4x3.IFCCARTESIANPOINTLIST2D, EntityTypesIfc4x3.IFCCARTESIANPOINTLIST3D, EntityTypesIfc4x3.IFCCARTESIANTRANSFORMATIONOPERATOR2D, EntityTypesIfc4x3.IFCCARTESIANTRANSFORMATIONOPERATOR3D, EntityTypesIfc4x3.IFCCARTESIANTRANSFORMATIONOPERATOR2DNONUNIFORM, EntityTypesIfc4x3.IFCCARTESIANTRANSFORMATIONOPERATOR3DNONUNIFORM, EntityTypesIfc4x3.IFCBLOCK, EntityTypesIfc4x3.IFCRECTANGULARPYRAMID, EntityTypesIfc4x3.IFCRIGHTCIRCULARCONE, EntityTypesIfc4x3.IFCRIGHTCIRCULARCYLINDER, EntityTypesIfc4x3.IFCSPHERE, EntityTypesIfc4x3.IFCLINE, EntityTypesIfc4x3.IFCPCURVE, EntityTypesIfc4x3.IFCPOLYNOMIALCURVE, EntityTypesIfc4x3.IFCSURFACECURVE, EntityTypesIfc4x3.IFCCOMPOSITECURVE, EntityTypesIfc4x3.IFCINDEXEDPOLYCURVE, EntityTypesIfc4x3.IFCPOLYLINE, EntityTypesIfc4x3.IFCTRIMMEDCURVE, EntityTypesIfc4x3.IFCBSPLINECURVEWITHKNOTS, EntityTypesIfc4x3.IFCRATIONALBSPLINECURVEWITHKNOTS, EntityTypesIfc4x3.IFCCOMPOSITECURVEONSURFACE, EntityTypesIfc4x3.IFCGRADIENTCURVE, EntityTypesIfc4x3.IFCSEGMENTEDREFERENCECURVE, EntityTypesIfc4x3.IFCBOUNDARYCURVE, EntityTypesIfc4x3.IFCOUTERBOUNDARYCURVE, EntityTypesIfc4x3.IFCCIRCLE, EntityTypesIfc4x3.IFCELLIPSE, EntityTypesIfc4x3.IFCOFFSETCURVE2D, EntityTypesIfc4x3.IFCOFFSETCURVE3D, EntityTypesIfc4x3.IFCOFFSETCURVEBYDISTANCES, EntityTypesIfc4x3.IFCCLOTHOID, EntityTypesIfc4x3.IFCCOSINESPIRAL, EntityTypesIfc4x3.IFCSECONDORDERPOLYNOMIALSPIRAL, EntityTypesIfc4x3.IFCSEVENTHORDERPOLYNOMIALSPIRAL, EntityTypesIfc4x3.IFCSINESPIRAL, EntityTypesIfc4x3.IFCTHIRDORDERPOLYNOMIALSPIRAL, EntityTypesIfc4x3.IFCINTERSECTIONCURVE, EntityTypesIfc4x3.IFCSEAMCURVE, EntityTypesIfc4x3.IFCGEOMETRICCURVESET, EntityTypesIfc4x3.IFCBOXEDHALFSPACE, EntityTypesIfc4x3.IFCPOLYGONALBOUNDEDHALFSPACE, EntityTypesIfc4x3.IFCLIGHTSOURCEAMBIENT, EntityTypesIfc4x3.IFCLIGHTSOURCEDIRECTIONAL, EntityTypesIfc4x3.IFCLIGHTSOURCEGONIOMETRIC, EntityTypesIfc4x3.IFCLIGHTSOURCEPOSITIONAL, EntityTypesIfc4x3.IFCLIGHTSOURCESPOT, EntityTypesIfc4x3.IFCAXIS1PLACEMENT, EntityTypesIfc4x3.IFCAXIS2PLACEMENT2D, EntityTypesIfc4x3.IFCAXIS2PLACEMENT3D, EntityTypesIfc4x3.IFCAXIS2PLACEMENTLINEAR, EntityTypesIfc4x3.IFCPLANARBOX, EntityTypesIfc4x3.IFCCARTESIANPOINT, EntityTypesIfc4x3.IFCPOINTBYDISTANCEEXPRESSION, EntityTypesIfc4x3.IFCPOINTONCURVE, EntityTypesIfc4x3.IFCPOINTONSURFACE, EntityTypesIfc4x3.IFCCOMPOSITECURVESEGMENT, EntityTypesIfc4x3.IFCCURVESEGMENT, EntityTypesIfc4x3.IFCREPARAMETRISEDCOMPOSITECURVESEGMENT, EntityTypesIfc4x3.IFCCSGSOLID, EntityTypesIfc4x3.IFCSWEPTDISKSOLID, EntityTypesIfc4x3.IFCADVANCEDBREP, EntityTypesIfc4x3.IFCFACETEDBREP, EntityTypesIfc4x3.IFCADVANCEDBREPWITHVOIDS, EntityTypesIfc4x3.IFCFACETEDBREPWITHVOIDS, EntityTypesIfc4x3.IFCSECTIONEDSOLIDHORIZONTAL, EntityTypesIfc4x3.IFCEXTRUDEDAREASOLID, EntityTypesIfc4x3.IFCREVOLVEDAREASOLID, EntityTypesIfc4x3.IFCFIXEDREFERENCESWEPTAREASOLID, EntityTypesIfc4x3.IFCSURFACECURVESWEPTAREASOLID, EntityTypesIfc4x3.IFCDIRECTRIXDERIVEDREFERENCESWEPTAREASOLID, EntityTypesIfc4x3.IFCEXTRUDEDAREASOLIDTAPERED, EntityTypesIfc4x3.IFCREVOLVEDAREASOLIDTAPERED, EntityTypesIfc4x3.IFCSWEPTDISKSOLIDPOLYGONAL, EntityTypesIfc4x3.IFCSECTIONEDSURFACE, EntityTypesIfc4x3.IFCCURVEBOUNDEDPLANE, EntityTypesIfc4x3.IFCCURVEBOUNDEDSURFACE, EntityTypesIfc4x3.IFCRECTANGULARTRIMMEDSURFACE, EntityTypesIfc4x3.IFCBSPLINESURFACEWITHKNOTS, EntityTypesIfc4x3.IFCRATIONALBSPLINESURFACEWITHKNOTS, EntityTypesIfc4x3.IFCCYLINDRICALSURFACE, EntityTypesIfc4x3.IFCPLANE, EntityTypesIfc4x3.IFCSPHERICALSURFACE, EntityTypesIfc4x3.IFCTOROIDALSURFACE, EntityTypesIfc4x3.IFCSURFACEOFLINEAREXTRUSION, EntityTypesIfc4x3.IFCSURFACEOFREVOLUTION, EntityTypesIfc4x3.IFCINDEXEDPOLYGONALFACE, EntityTypesIfc4x3.IFCINDEXEDPOLYGONALFACEWITHVOIDS, EntityTypesIfc4x3.IFCPOLYGONALFACESET, EntityTypesIfc4x3.IFCTRIANGULATEDFACESET, EntityTypesIfc4x3.IFCTRIANGULATEDIRREGULARNETWORK, EntityTypesIfc4x3.IFCTEXTLITERALWITHEXTENT ]

  public static readonly expectedType: EntityTypesIfc4x3 =
    EntityTypesIfc4x3.IFCGEOMETRICREPRESENTATIONITEM
}
