/* This is generated code, don't modify. Regenerate with
 * `yarn code-gen-ifc4x3-compat` (scripts/gen_ifc4x3_decode_compat.mjs)
 * from scripts/schemas/IFC4.exp and scripts/schemas/IFC4X3_ADD2.exp. */
import { Ifc4x3DecodeCompat } from '../ifc4x3_decode_compat_derive'

const DECODE_COMPAT: Ifc4x3DecodeCompat = {
  "compatible": [
    "IFCABSORBEDDOSEMEASURE",
    "IFCACCELERATIONMEASURE",
    "IFCACTIONREQUEST",
    "IFCACTOR",
    "IFCACTORROLE",
    "IFCACTUATOR",
    "IFCACTUATORTYPE",
    "IFCADVANCEDBREP",
    "IFCADVANCEDBREPWITHVOIDS",
    "IFCADVANCEDFACE",
    "IFCAIRTERMINAL",
    "IFCAIRTERMINALBOX",
    "IFCAIRTERMINALBOXTYPE",
    "IFCAIRTERMINALTYPE",
    "IFCAIRTOAIRHEATRECOVERY",
    "IFCAIRTOAIRHEATRECOVERYTYPE",
    "IFCAMOUNTOFSUBSTANCEMEASURE",
    "IFCANGULARVELOCITYMEASURE",
    "IFCANNOTATIONFILLAREA",
    "IFCAPPLICATION",
    "IFCAPPROVAL",
    "IFCAPPROVALRELATIONSHIP",
    "IFCARBITRARYCLOSEDPROFILEDEF",
    "IFCARBITRARYOPENPROFILEDEF",
    "IFCARBITRARYPROFILEDEFWITHVOIDS",
    "IFCARCINDEX",
    "IFCAREADENSITYMEASURE",
    "IFCAREAMEASURE",
    "IFCASSET",
    "IFCASYMMETRICISHAPEPROFILEDEF",
    "IFCAXIS1PLACEMENT",
    "IFCAXIS2PLACEMENT2D",
    "IFCAXIS2PLACEMENT3D",
    "IFCBINARY",
    "IFCBLOBTEXTURE",
    "IFCBLOCK",
    "IFCBOILER",
    "IFCBOILERTYPE",
    "IFCBOOLEAN",
    "IFCBOOLEANCLIPPINGRESULT",
    "IFCBOOLEANRESULT",
    "IFCBOUNDARYCURVE",
    "IFCBOUNDARYEDGECONDITION",
    "IFCBOUNDARYFACECONDITION",
    "IFCBOUNDARYNODECONDITION",
    "IFCBOUNDARYNODECONDITIONWARPING",
    "IFCBOUNDINGBOX",
    "IFCBOXALIGNMENT",
    "IFCBOXEDHALFSPACE",
    "IFCBSPLINECURVEWITHKNOTS",
    "IFCBSPLINESURFACEWITHKNOTS",
    "IFCBUILDING",
    "IFCBUILDINGELEMENTPROXY",
    "IFCBUILDINGELEMENTPROXYTYPE",
    "IFCBUILDINGSTOREY",
    "IFCBUILDINGSYSTEM",
    "IFCBURNER",
    "IFCBURNERTYPE",
    "IFCCARDINALPOINTREFERENCE",
    "IFCCARTESIANPOINT",
    "IFCCARTESIANTRANSFORMATIONOPERATOR2D",
    "IFCCARTESIANTRANSFORMATIONOPERATOR2DNONUNIFORM",
    "IFCCARTESIANTRANSFORMATIONOPERATOR3D",
    "IFCCARTESIANTRANSFORMATIONOPERATOR3DNONUNIFORM",
    "IFCCENTERLINEPROFILEDEF",
    "IFCCHILLER",
    "IFCCHILLERTYPE",
    "IFCCHIMNEY",
    "IFCCHIMNEYTYPE",
    "IFCCIRCLE",
    "IFCCIRCLEHOLLOWPROFILEDEF",
    "IFCCIRCLEPROFILEDEF",
    "IFCCIVILELEMENT",
    "IFCCIVILELEMENTTYPE",
    "IFCCLASSIFICATION",
    "IFCCLASSIFICATIONREFERENCE",
    "IFCCLOSEDSHELL",
    "IFCCOIL",
    "IFCCOILTYPE",
    "IFCCOLOURRGB",
    "IFCCOLOURRGBLIST",
    "IFCCOMPLEXNUMBER",
    "IFCCOMPLEXPROPERTY",
    "IFCCOMPLEXPROPERTYTEMPLATE",
    "IFCCOMPOSITECURVE",
    "IFCCOMPOSITECURVEONSURFACE",
    "IFCCOMPOSITECURVESEGMENT",
    "IFCCOMPOSITEPROFILEDEF",
    "IFCCOMPOUNDPLANEANGLEMEASURE",
    "IFCCOMPRESSOR",
    "IFCCOMPRESSORTYPE",
    "IFCCONDENSER",
    "IFCCONDENSERTYPE",
    "IFCCONNECTEDFACESET",
    "IFCCONNECTIONCURVEGEOMETRY",
    "IFCCONNECTIONPOINTECCENTRICITY",
    "IFCCONNECTIONPOINTGEOMETRY",
    "IFCCONNECTIONSURFACEGEOMETRY",
    "IFCCONNECTIONVOLUMEGEOMETRY",
    "IFCCONSTRUCTIONEQUIPMENTRESOURCE",
    "IFCCONSTRUCTIONEQUIPMENTRESOURCETYPE",
    "IFCCONSTRUCTIONMATERIALRESOURCE",
    "IFCCONSTRUCTIONMATERIALRESOURCETYPE",
    "IFCCONSTRUCTIONPRODUCTRESOURCE",
    "IFCCONSTRUCTIONPRODUCTRESOURCETYPE",
    "IFCCONTEXTDEPENDENTMEASURE",
    "IFCCONTEXTDEPENDENTUNIT",
    "IFCCONTROLLER",
    "IFCCONTROLLERTYPE",
    "IFCCONVERSIONBASEDUNIT",
    "IFCCONVERSIONBASEDUNITWITHOFFSET",
    "IFCCOOLEDBEAM",
    "IFCCOOLEDBEAMTYPE",
    "IFCCOOLINGTOWER",
    "IFCCOOLINGTOWERTYPE",
    "IFCCOSTITEM",
    "IFCCOSTSCHEDULE",
    "IFCCREWRESOURCE",
    "IFCCREWRESOURCETYPE",
    "IFCCSGSOLID",
    "IFCCSHAPEPROFILEDEF",
    "IFCCURRENCYRELATIONSHIP",
    "IFCCURTAINWALL",
    "IFCCURTAINWALLTYPE",
    "IFCCURVATUREMEASURE",
    "IFCCURVEBOUNDEDPLANE",
    "IFCCURVEBOUNDEDSURFACE",
    "IFCCURVESTYLE",
    "IFCCURVESTYLEFONT",
    "IFCCURVESTYLEFONTANDSCALING",
    "IFCCURVESTYLEFONTPATTERN",
    "IFCCYLINDRICALSURFACE",
    "IFCDAMPER",
    "IFCDAMPERTYPE",
    "IFCDATE",
    "IFCDATETIME",
    "IFCDAYINMONTHNUMBER",
    "IFCDAYINWEEKNUMBER",
    "IFCDERIVEDPROFILEDEF",
    "IFCDERIVEDUNITELEMENT",
    "IFCDESCRIPTIVEMEASURE",
    "IFCDIMENSIONALEXPONENTS",
    "IFCDIMENSIONCOUNT",
    "IFCDIRECTION",
    "IFCDISTRIBUTIONCHAMBERELEMENT",
    "IFCDISTRIBUTIONCHAMBERELEMENTTYPE",
    "IFCDISTRIBUTIONCONTROLELEMENT",
    "IFCDISTRIBUTIONELEMENT",
    "IFCDISTRIBUTIONELEMENTTYPE",
    "IFCDISTRIBUTIONFLOWELEMENT",
    "IFCDOCUMENTINFORMATION",
    "IFCDOCUMENTINFORMATIONRELATIONSHIP",
    "IFCDOCUMENTREFERENCE",
    "IFCDOORLININGPROPERTIES",
    "IFCDOORPANELPROPERTIES",
    "IFCDOSEEQUIVALENTMEASURE",
    "IFCDRAUGHTINGPREDEFINEDCOLOUR",
    "IFCDRAUGHTINGPREDEFINEDCURVEFONT",
    "IFCDUCTFITTING",
    "IFCDUCTFITTINGTYPE",
    "IFCDUCTSEGMENT",
    "IFCDUCTSEGMENTTYPE",
    "IFCDUCTSILENCER",
    "IFCDUCTSILENCERTYPE",
    "IFCDURATION",
    "IFCDYNAMICVISCOSITYMEASURE",
    "IFCEDGE",
    "IFCEDGECURVE",
    "IFCEDGELOOP",
    "IFCELECTRICAPPLIANCE",
    "IFCELECTRICAPPLIANCETYPE",
    "IFCELECTRICCAPACITANCEMEASURE",
    "IFCELECTRICCHARGEMEASURE",
    "IFCELECTRICCONDUCTANCEMEASURE",
    "IFCELECTRICCURRENTMEASURE",
    "IFCELECTRICDISTRIBUTIONBOARD",
    "IFCELECTRICDISTRIBUTIONBOARDTYPE",
    "IFCELECTRICGENERATOR",
    "IFCELECTRICGENERATORTYPE",
    "IFCELECTRICMOTOR",
    "IFCELECTRICMOTORTYPE",
    "IFCELECTRICRESISTANCEMEASURE",
    "IFCELECTRICTIMECONTROL",
    "IFCELECTRICTIMECONTROLTYPE",
    "IFCELECTRICVOLTAGEMEASURE",
    "IFCELEMENTQUANTITY",
    "IFCELLIPSE",
    "IFCELLIPSEPROFILEDEF",
    "IFCENERGYCONVERSIONDEVICE",
    "IFCENERGYMEASURE",
    "IFCENGINE",
    "IFCENGINETYPE",
    "IFCEVAPORATIVECOOLER",
    "IFCEVAPORATIVECOOLERTYPE",
    "IFCEVAPORATOR",
    "IFCEVAPORATORTYPE",
    "IFCEVENT",
    "IFCEVENTTIME",
    "IFCEVENTTYPE",
    "IFCEXTERNALLYDEFINEDHATCHSTYLE",
    "IFCEXTERNALLYDEFINEDSURFACESTYLE",
    "IFCEXTERNALLYDEFINEDTEXTFONT",
    "IFCEXTERNALREFERENCERELATIONSHIP",
    "IFCEXTERNALSPATIALELEMENT",
    "IFCEXTRUDEDAREASOLID",
    "IFCEXTRUDEDAREASOLIDTAPERED",
    "IFCFACE",
    "IFCFACEBASEDSURFACEMODEL",
    "IFCFACEBOUND",
    "IFCFACEOUTERBOUND",
    "IFCFACESURFACE",
    "IFCFACETEDBREP",
    "IFCFACETEDBREPWITHVOIDS",
    "IFCFAILURECONNECTIONCONDITION",
    "IFCFAN",
    "IFCFANTYPE",
    "IFCFASTENER",
    "IFCFASTENERTYPE",
    "IFCFILLAREASTYLE",
    "IFCFILLAREASTYLEHATCHING",
    "IFCFILLAREASTYLETILES",
    "IFCFILTER",
    "IFCFILTERTYPE",
    "IFCFLOWCONTROLLER",
    "IFCFLOWFITTING",
    "IFCFLOWMETER",
    "IFCFLOWMETERTYPE",
    "IFCFLOWMOVINGDEVICE",
    "IFCFLOWSEGMENT",
    "IFCFLOWSTORAGEDEVICE",
    "IFCFLOWTERMINAL",
    "IFCFLOWTREATMENTDEVICE",
    "IFCFONTSTYLE",
    "IFCFONTVARIANT",
    "IFCFONTWEIGHT",
    "IFCFOOTING",
    "IFCFOOTINGTYPE",
    "IFCFORCEMEASURE",
    "IFCFREQUENCYMEASURE",
    "IFCFURNISHINGELEMENT",
    "IFCFURNISHINGELEMENTTYPE",
    "IFCGEOMETRICCURVESET",
    "IFCGEOMETRICREPRESENTATIONCONTEXT",
    "IFCGEOMETRICREPRESENTATIONSUBCONTEXT",
    "IFCGEOMETRICSET",
    "IFCGLOBALLYUNIQUEID",
    "IFCGRID",
    "IFCGRIDAXIS",
    "IFCGROUP",
    "IFCHALFSPACESOLID",
    "IFCHEATFLUXDENSITYMEASURE",
    "IFCHEATINGVALUEMEASURE",
    "IFCHUMIDIFIER",
    "IFCHUMIDIFIERTYPE",
    "IFCIDENTIFIER",
    "IFCILLUMINANCEMEASURE",
    "IFCIMAGETEXTURE",
    "IFCINDEXEDCOLOURMAP",
    "IFCINDEXEDPOLYCURVE",
    "IFCINDEXEDPOLYGONALFACE",
    "IFCINDEXEDPOLYGONALFACEWITHVOIDS",
    "IFCINDEXEDTRIANGLETEXTUREMAP",
    "IFCINDUCTANCEMEASURE",
    "IFCINTEGER",
    "IFCINTEGERCOUNTRATEMEASURE",
    "IFCINTERCEPTOR",
    "IFCINTERCEPTORTYPE",
    "IFCINTERSECTIONCURVE",
    "IFCINVENTORY",
    "IFCIONCONCENTRATIONMEASURE",
    "IFCIRREGULARTIMESERIES",
    "IFCIRREGULARTIMESERIESVALUE",
    "IFCISHAPEPROFILEDEF",
    "IFCISOTHERMALMOISTURECAPACITYMEASURE",
    "IFCJUNCTIONBOX",
    "IFCJUNCTIONBOXTYPE",
    "IFCKINEMATICVISCOSITYMEASURE",
    "IFCLABEL",
    "IFCLABORRESOURCE",
    "IFCLABORRESOURCETYPE",
    "IFCLAGTIME",
    "IFCLAMP",
    "IFCLAMPTYPE",
    "IFCLANGUAGEID",
    "IFCLENGTHMEASURE",
    "IFCLIBRARYINFORMATION",
    "IFCLIBRARYREFERENCE",
    "IFCLIGHTDISTRIBUTIONDATA",
    "IFCLIGHTFIXTURE",
    "IFCLIGHTFIXTURETYPE",
    "IFCLIGHTINTENSITYDISTRIBUTION",
    "IFCLIGHTSOURCEAMBIENT",
    "IFCLIGHTSOURCEDIRECTIONAL",
    "IFCLIGHTSOURCEGONIOMETRIC",
    "IFCLIGHTSOURCEPOSITIONAL",
    "IFCLIGHTSOURCESPOT",
    "IFCLINE",
    "IFCLINEARFORCEMEASURE",
    "IFCLINEARMOMENTMEASURE",
    "IFCLINEARSTIFFNESSMEASURE",
    "IFCLINEARVELOCITYMEASURE",
    "IFCLINEINDEX",
    "IFCLOCALPLACEMENT",
    "IFCLOGICAL",
    "IFCLOOP",
    "IFCLSHAPEPROFILEDEF",
    "IFCLUMINOUSFLUXMEASURE",
    "IFCLUMINOUSINTENSITYDISTRIBUTIONMEASURE",
    "IFCLUMINOUSINTENSITYMEASURE",
    "IFCMAGNETICFLUXDENSITYMEASURE",
    "IFCMAGNETICFLUXMEASURE",
    "IFCMAPCONVERSION",
    "IFCMAPPEDITEM",
    "IFCMASSDENSITYMEASURE",
    "IFCMASSFLOWRATEMEASURE",
    "IFCMASSMEASURE",
    "IFCMASSPERLENGTHMEASURE",
    "IFCMATERIAL",
    "IFCMATERIALCLASSIFICATIONRELATIONSHIP",
    "IFCMATERIALCONSTITUENT",
    "IFCMATERIALCONSTITUENTSET",
    "IFCMATERIALDEFINITIONREPRESENTATION",
    "IFCMATERIALLAYER",
    "IFCMATERIALLAYERSET",
    "IFCMATERIALLAYERSETUSAGE",
    "IFCMATERIALLAYERWITHOFFSETS",
    "IFCMATERIALLIST",
    "IFCMATERIALPROFILE",
    "IFCMATERIALPROFILESET",
    "IFCMATERIALPROFILESETUSAGE",
    "IFCMATERIALPROFILESETUSAGETAPERING",
    "IFCMATERIALPROFILEWITHOFFSETS",
    "IFCMATERIALPROPERTIES",
    "IFCMATERIALRELATIONSHIP",
    "IFCMEASUREWITHUNIT",
    "IFCMEDICALDEVICE",
    "IFCMEDICALDEVICETYPE",
    "IFCMETRIC",
    "IFCMIRROREDPROFILEDEF",
    "IFCMODULUSOFELASTICITYMEASURE",
    "IFCMODULUSOFLINEARSUBGRADEREACTIONMEASURE",
    "IFCMODULUSOFROTATIONALSUBGRADEREACTIONMEASURE",
    "IFCMODULUSOFSUBGRADEREACTIONMEASURE",
    "IFCMOISTUREDIFFUSIVITYMEASURE",
    "IFCMOLECULARWEIGHTMEASURE",
    "IFCMOMENTOFINERTIAMEASURE",
    "IFCMONETARYMEASURE",
    "IFCMONETARYUNIT",
    "IFCMONTHINYEARNUMBER",
    "IFCMOTORCONNECTION",
    "IFCMOTORCONNECTIONTYPE",
    "IFCNONNEGATIVELENGTHMEASURE",
    "IFCNORMALISEDRATIOMEASURE",
    "IFCNUMERICMEASURE",
    "IFCOBJECTIVE",
    "IFCOCCUPANT",
    "IFCOFFSETCURVE2D",
    "IFCOFFSETCURVE3D",
    "IFCOPENINGELEMENT",
    "IFCOPENSHELL",
    "IFCORGANIZATION",
    "IFCORGANIZATIONRELATIONSHIP",
    "IFCORIENTEDEDGE",
    "IFCOUTERBOUNDARYCURVE",
    "IFCOUTLET",
    "IFCOUTLETTYPE",
    "IFCOWNERHISTORY",
    "IFCPARAMETERVALUE",
    "IFCPATH",
    "IFCPCURVE",
    "IFCPERFORMANCEHISTORY",
    "IFCPERMEABLECOVERINGPROPERTIES",
    "IFCPERMIT",
    "IFCPERSON",
    "IFCPERSONANDORGANIZATION",
    "IFCPHMEASURE",
    "IFCPHYSICALCOMPLEXQUANTITY",
    "IFCPILE",
    "IFCPILETYPE",
    "IFCPIPEFITTING",
    "IFCPIPEFITTINGTYPE",
    "IFCPIPESEGMENT",
    "IFCPIPESEGMENTTYPE",
    "IFCPIXELTEXTURE",
    "IFCPLANARBOX",
    "IFCPLANAREXTENT",
    "IFCPLANARFORCEMEASURE",
    "IFCPLANE",
    "IFCPLANEANGLEMEASURE",
    "IFCPOINTONCURVE",
    "IFCPOINTONSURFACE",
    "IFCPOLYGONALBOUNDEDHALFSPACE",
    "IFCPOLYGONALFACESET",
    "IFCPOLYLINE",
    "IFCPOLYLOOP",
    "IFCPOSITIVEINTEGER",
    "IFCPOSITIVELENGTHMEASURE",
    "IFCPOSITIVEPLANEANGLEMEASURE",
    "IFCPOSITIVERATIOMEASURE",
    "IFCPOSTALADDRESS",
    "IFCPOWERMEASURE",
    "IFCPRESENTABLETEXT",
    "IFCPRESENTATIONLAYERASSIGNMENT",
    "IFCPRESENTATIONLAYERWITHSTYLE",
    "IFCPRESSUREMEASURE",
    "IFCPROCEDURE",
    "IFCPROCEDURETYPE",
    "IFCPRODUCTDEFINITIONSHAPE",
    "IFCPROFILEDEF",
    "IFCPROFILEPROPERTIES",
    "IFCPROJECT",
    "IFCPROJECTLIBRARY",
    "IFCPROJECTORDER",
    "IFCPROPERTYBOUNDEDVALUE",
    "IFCPROPERTYDEPENDENCYRELATIONSHIP",
    "IFCPROPERTYENUMERATEDVALUE",
    "IFCPROPERTYENUMERATION",
    "IFCPROPERTYLISTVALUE",
    "IFCPROPERTYREFERENCEVALUE",
    "IFCPROPERTYSET",
    "IFCPROPERTYSINGLEVALUE",
    "IFCPROPERTYTABLEVALUE",
    "IFCPROTECTIVEDEVICETRIPPINGUNIT",
    "IFCPROTECTIVEDEVICETRIPPINGUNITTYPE",
    "IFCPUMP",
    "IFCPUMPTYPE",
    "IFCQUANTITYAREA",
    "IFCQUANTITYLENGTH",
    "IFCQUANTITYTIME",
    "IFCQUANTITYVOLUME",
    "IFCQUANTITYWEIGHT",
    "IFCRADIOACTIVITYMEASURE",
    "IFCRAMP",
    "IFCRAMPFLIGHT",
    "IFCRAMPFLIGHTTYPE",
    "IFCRAMPTYPE",
    "IFCRATIOMEASURE",
    "IFCRATIONALBSPLINECURVEWITHKNOTS",
    "IFCRATIONALBSPLINESURFACEWITHKNOTS",
    "IFCREAL",
    "IFCRECTANGLEHOLLOWPROFILEDEF",
    "IFCRECTANGLEPROFILEDEF",
    "IFCRECTANGULARPYRAMID",
    "IFCRECTANGULARTRIMMEDSURFACE",
    "IFCRECURRENCEPATTERN",
    "IFCREFERENCE",
    "IFCREGULARTIMESERIES",
    "IFCREINFORCEMENTDEFINITIONPROPERTIES",
    "IFCREINFORCINGMESH",
    "IFCREINFORCINGMESHTYPE",
    "IFCRELAGGREGATES",
    "IFCRELASSOCIATESAPPROVAL",
    "IFCRELASSOCIATESCLASSIFICATION",
    "IFCRELASSOCIATESCONSTRAINT",
    "IFCRELASSOCIATESDOCUMENT",
    "IFCRELASSOCIATESLIBRARY",
    "IFCRELASSOCIATESMATERIAL",
    "IFCRELCONNECTSELEMENTS",
    "IFCRELCONNECTSPATHELEMENTS",
    "IFCRELCONNECTSPORTS",
    "IFCRELCONNECTSPORTTOELEMENT",
    "IFCRELCONNECTSSTRUCTURALACTIVITY",
    "IFCRELCONNECTSSTRUCTURALMEMBER",
    "IFCRELCONNECTSWITHECCENTRICITY",
    "IFCRELCONNECTSWITHREALIZINGELEMENTS",
    "IFCRELCONTAINEDINSPATIALSTRUCTURE",
    "IFCRELCOVERSBLDGELEMENTS",
    "IFCRELCOVERSSPACES",
    "IFCRELDECLARES",
    "IFCRELDEFINESBYOBJECT",
    "IFCRELDEFINESBYPROPERTIES",
    "IFCRELDEFINESBYTEMPLATE",
    "IFCRELDEFINESBYTYPE",
    "IFCRELFILLSELEMENT",
    "IFCRELFLOWCONTROLELEMENTS",
    "IFCRELNESTS",
    "IFCRELPROJECTSELEMENT",
    "IFCRELREFERENCEDINSPATIALSTRUCTURE",
    "IFCRELSEQUENCE",
    "IFCRELSERVICESBUILDINGS",
    "IFCRELSPACEBOUNDARY",
    "IFCRELSPACEBOUNDARY1STLEVEL",
    "IFCRELSPACEBOUNDARY2NDLEVEL",
    "IFCRELVOIDSELEMENT",
    "IFCREPARAMETRISEDCOMPOSITECURVESEGMENT",
    "IFCREPRESENTATIONMAP",
    "IFCRESOURCEAPPROVALRELATIONSHIP",
    "IFCRESOURCECONSTRAINTRELATIONSHIP",
    "IFCRESOURCETIME",
    "IFCREVOLVEDAREASOLID",
    "IFCREVOLVEDAREASOLIDTAPERED",
    "IFCRIGHTCIRCULARCONE",
    "IFCRIGHTCIRCULARCYLINDER",
    "IFCROOF",
    "IFCROOFTYPE",
    "IFCROTATIONALFREQUENCYMEASURE",
    "IFCROTATIONALMASSMEASURE",
    "IFCROTATIONALSTIFFNESSMEASURE",
    "IFCROUNDEDRECTANGLEPROFILEDEF",
    "IFCSANITARYTERMINAL",
    "IFCSANITARYTERMINALTYPE",
    "IFCSEAMCURVE",
    "IFCSECTIONALAREAINTEGRALMEASURE",
    "IFCSECTIONEDSPINE",
    "IFCSECTIONMODULUSMEASURE",
    "IFCSECTIONPROPERTIES",
    "IFCSECTIONREINFORCEMENTPROPERTIES",
    "IFCSHADINGDEVICE",
    "IFCSHADINGDEVICETYPE",
    "IFCSHAPEASPECT",
    "IFCSHAPEREPRESENTATION",
    "IFCSHEARMODULUSMEASURE",
    "IFCSHELLBASEDSURFACEMODEL",
    "IFCSITE",
    "IFCSIUNIT",
    "IFCSLIPPAGECONNECTIONCONDITION",
    "IFCSOLARDEVICE",
    "IFCSOLARDEVICETYPE",
    "IFCSOLIDANGLEMEASURE",
    "IFCSOUNDPOWERLEVELMEASURE",
    "IFCSOUNDPOWERMEASURE",
    "IFCSOUNDPRESSURELEVELMEASURE",
    "IFCSOUNDPRESSUREMEASURE",
    "IFCSPACEHEATER",
    "IFCSPACEHEATERTYPE",
    "IFCSPECIFICHEATCAPACITYMEASURE",
    "IFCSPECULAREXPONENT",
    "IFCSPECULARROUGHNESS",
    "IFCSPHERE",
    "IFCSPHERICALSURFACE",
    "IFCSTACKTERMINAL",
    "IFCSTACKTERMINALTYPE",
    "IFCSTAIRFLIGHT",
    "IFCSTAIRFLIGHTTYPE",
    "IFCSTRIPPEDOPTIONAL",
    "IFCSTRUCTURALANALYSISMODEL",
    "IFCSTRUCTURALCURVEACTION",
    "IFCSTRUCTURALCURVECONNECTION",
    "IFCSTRUCTURALCURVEMEMBER",
    "IFCSTRUCTURALCURVEMEMBERVARYING",
    "IFCSTRUCTURALCURVEREACTION",
    "IFCSTRUCTURALLINEARACTION",
    "IFCSTRUCTURALLOADCASE",
    "IFCSTRUCTURALLOADCONFIGURATION",
    "IFCSTRUCTURALLOADGROUP",
    "IFCSTRUCTURALLOADLINEARFORCE",
    "IFCSTRUCTURALLOADPLANARFORCE",
    "IFCSTRUCTURALLOADSINGLEDISPLACEMENT",
    "IFCSTRUCTURALLOADSINGLEDISPLACEMENTDISTORTION",
    "IFCSTRUCTURALLOADSINGLEFORCE",
    "IFCSTRUCTURALLOADSINGLEFORCEWARPING",
    "IFCSTRUCTURALLOADTEMPERATURE",
    "IFCSTRUCTURALPLANARACTION",
    "IFCSTRUCTURALPOINTACTION",
    "IFCSTRUCTURALPOINTCONNECTION",
    "IFCSTRUCTURALPOINTREACTION",
    "IFCSTRUCTURALRESULTGROUP",
    "IFCSTRUCTURALSURFACEACTION",
    "IFCSTRUCTURALSURFACECONNECTION",
    "IFCSTRUCTURALSURFACEMEMBER",
    "IFCSTRUCTURALSURFACEMEMBERVARYING",
    "IFCSTRUCTURALSURFACEREACTION",
    "IFCSTYLEDITEM",
    "IFCSTYLEDREPRESENTATION",
    "IFCSUBCONTRACTRESOURCE",
    "IFCSUBCONTRACTRESOURCETYPE",
    "IFCSUBEDGE",
    "IFCSURFACECURVE",
    "IFCSURFACEOFLINEAREXTRUSION",
    "IFCSURFACEOFREVOLUTION",
    "IFCSURFACEREINFORCEMENTAREA",
    "IFCSURFACESTYLE",
    "IFCSURFACESTYLELIGHTING",
    "IFCSURFACESTYLEREFRACTION",
    "IFCSURFACESTYLESHADING",
    "IFCSURFACESTYLEWITHTEXTURES",
    "IFCSWEPTDISKSOLID",
    "IFCSWEPTDISKSOLIDPOLYGONAL",
    "IFCSYSTEM",
    "IFCTABLE",
    "IFCTABLECOLUMN",
    "IFCTABLEROW",
    "IFCTASKTIME",
    "IFCTASKTIMERECURRING",
    "IFCTELECOMADDRESS",
    "IFCTEMPERATUREGRADIENTMEASURE",
    "IFCTEMPERATURERATEOFCHANGEMEASURE",
    "IFCTENDON",
    "IFCTENDONANCHOR",
    "IFCTENDONANCHORTYPE",
    "IFCTENDONTYPE",
    "IFCTEXT",
    "IFCTEXTALIGNMENT",
    "IFCTEXTDECORATION",
    "IFCTEXTFONTNAME",
    "IFCTEXTLITERAL",
    "IFCTEXTLITERALWITHEXTENT",
    "IFCTEXTSTYLE",
    "IFCTEXTSTYLEFONTMODEL",
    "IFCTEXTSTYLEFORDEFINEDFONT",
    "IFCTEXTSTYLETEXTMODEL",
    "IFCTEXTTRANSFORMATION",
    "IFCTEXTURECOORDINATEGENERATOR",
    "IFCTEXTUREMAP",
    "IFCTEXTUREVERTEX",
    "IFCTEXTUREVERTEXLIST",
    "IFCTHERMALADMITTANCEMEASURE",
    "IFCTHERMALCONDUCTIVITYMEASURE",
    "IFCTHERMALEXPANSIONCOEFFICIENTMEASURE",
    "IFCTHERMALRESISTANCEMEASURE",
    "IFCTHERMALTRANSMITTANCEMEASURE",
    "IFCTHERMODYNAMICTEMPERATUREMEASURE",
    "IFCTIME",
    "IFCTIMEMEASURE",
    "IFCTIMEPERIOD",
    "IFCTIMESERIESVALUE",
    "IFCTIMESTAMP",
    "IFCTOPOLOGYREPRESENTATION",
    "IFCTOROIDALSURFACE",
    "IFCTORQUEMEASURE",
    "IFCTRAPEZIUMPROFILEDEF",
    "IFCTRIANGULATEDFACESET",
    "IFCTRIMMEDCURVE",
    "IFCTSHAPEPROFILEDEF",
    "IFCTUBEBUNDLE",
    "IFCTUBEBUNDLETYPE",
    "IFCTYPEOBJECT",
    "IFCTYPEPRODUCT",
    "IFCUNITARYEQUIPMENT",
    "IFCUNITARYEQUIPMENTTYPE",
    "IFCUNITASSIGNMENT",
    "IFCURIREFERENCE",
    "IFCUSHAPEPROFILEDEF",
    "IFCVALVE",
    "IFCVALVETYPE",
    "IFCVAPORPERMEABILITYMEASURE",
    "IFCVECTOR",
    "IFCVERTEX",
    "IFCVERTEXLOOP",
    "IFCVERTEXPOINT",
    "IFCVIRTUALGRIDINTERSECTION",
    "IFCVOIDINGFEATURE",
    "IFCVOLUMEMEASURE",
    "IFCVOLUMETRICFLOWRATEMEASURE",
    "IFCWARPINGCONSTANTMEASURE",
    "IFCWARPINGMOMENTMEASURE",
    "IFCWASTETERMINAL",
    "IFCWASTETERMINALTYPE",
    "IFCWINDOW",
    "IFCWINDOWLININGPROPERTIES",
    "IFCWINDOWPANELPROPERTIES",
    "IFCWINDOWTYPE",
    "IFCWORKCALENDAR",
    "IFCWORKPLAN",
    "IFCWORKSCHEDULE",
    "IFCWORKTIME",
    "IFCZONE",
    "IFCZSHAPEPROFILEDEF"
  ],
  "relaxed": {
    "IFCACTUATOR": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCADVANCEDFACE": [
      "1 FaceSurface: (c) IFCSURFACE widens IFCSURFACE with IFC4X3-only types"
    ],
    "IFCAIRTERMINAL": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCAIRTERMINALBOX": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCAIRTOAIRHEATRECOVERY": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCANNOTATIONFILLAREA": [
      "0 OuterBoundary: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types",
      "1 InnerBoundaries: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types"
    ],
    "IFCARBITRARYCLOSEDPROFILEDEF": [
      "2 OuterCurve: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types"
    ],
    "IFCARBITRARYOPENPROFILEDEF": [
      "2 Curve: (c) IFCBOUNDEDCURVE widens IFCBOUNDEDCURVE with IFC4X3-only types"
    ],
    "IFCARBITRARYPROFILEDEFWITHVOIDS": [
      "2 OuterCurve: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types",
      "3 InnerCurves: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types"
    ],
    "IFCAXIS1PLACEMENT": [
      "0 Location: (c) IFCPOINT widens IFCCARTESIANPOINT; loud: IFCPOINTONCURVE,IFCPOINTONSURFACE"
    ],
    "IFCAXIS2PLACEMENT2D": [
      "0 Location: (c) IFCPOINT widens IFCCARTESIANPOINT; loud: IFCPOINTONCURVE,IFCPOINTONSURFACE"
    ],
    "IFCAXIS2PLACEMENT3D": [
      "0 Location: (c) IFCPOINT widens IFCCARTESIANPOINT; loud: IFCPOINTONCURVE,IFCPOINTONSURFACE"
    ],
    "IFCBOILER": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCBOOLEANCLIPPINGRESULT": [
      "1 FirstOperand: (c) IFCBOOLEANOPERAND widens IFCBOOLEANOPERAND with IFC4X3-only types",
      "2 SecondOperand: (c) IFCBOOLEANOPERAND widens IFCBOOLEANOPERAND with IFC4X3-only types"
    ],
    "IFCBOOLEANRESULT": [
      "1 FirstOperand: (c) IFCBOOLEANOPERAND widens IFCBOOLEANOPERAND with IFC4X3-only types",
      "2 SecondOperand: (c) IFCBOOLEANOPERAND widens IFCBOOLEANOPERAND with IFC4X3-only types"
    ],
    "IFCBOUNDARYCURVE": [
      "0 Segments: (c) IFCSEGMENT widens IFCCOMPOSITECURVESEGMENT with IFC4X3-only types"
    ],
    "IFCBOXEDHALFSPACE": [
      "0 BaseSurface: (c) IFCSURFACE widens IFCSURFACE with IFC4X3-only types"
    ],
    "IFCBUILDING": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCBUILDINGELEMENTPROXY": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCBUILDINGSTOREY": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCBURNER": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCCENTERLINEPROFILEDEF": [
      "2 Curve: (c) IFCBOUNDEDCURVE widens IFCBOUNDEDCURVE with IFC4X3-only types"
    ],
    "IFCCHILLER": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCCHIMNEY": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCCIVILELEMENT": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCCLASSIFICATION": [
      "5 Location: (d) renamed Specification in ADD2"
    ],
    "IFCCOIL": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCCOMPLEXPROPERTY": [
      "1 Description: (d) renamed Specification in ADD2"
    ],
    "IFCCOMPOSITECURVE": [
      "0 Segments: (c) IFCSEGMENT widens IFCCOMPOSITECURVESEGMENT with IFC4X3-only types"
    ],
    "IFCCOMPOSITECURVEONSURFACE": [
      "0 Segments: (c) IFCSEGMENT widens IFCCOMPOSITECURVESEGMENT with IFC4X3-only types"
    ],
    "IFCCOMPOSITECURVESEGMENT": [
      "2 ParentCurve: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types"
    ],
    "IFCCOMPOSITEPROFILEDEF": [
      "2 Profiles: (c) IFCPROFILEDEF widens IFCPROFILEDEF with IFC4X3-only types"
    ],
    "IFCCOMPRESSOR": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCCONDENSER": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCCONNECTIONCURVEGEOMETRY": [
      "0 CurveOnRelatingElement: (c) IFCCURVEOREDGECURVE widens IFCCURVEOREDGECURVE with IFC4X3-only types",
      "1 CurveOnRelatedElement: (c) IFCCURVEOREDGECURVE widens IFCCURVEOREDGECURVE with IFC4X3-only types"
    ],
    "IFCCONNECTIONPOINTECCENTRICITY": [
      "0 PointOnRelatingElement: (c) IFCPOINTORVERTEXPOINT widens IFCPOINTORVERTEXPOINT with IFC4X3-only types",
      "1 PointOnRelatedElement: (c) IFCPOINTORVERTEXPOINT widens IFCPOINTORVERTEXPOINT with IFC4X3-only types"
    ],
    "IFCCONNECTIONPOINTGEOMETRY": [
      "0 PointOnRelatingElement: (c) IFCPOINTORVERTEXPOINT widens IFCPOINTORVERTEXPOINT with IFC4X3-only types",
      "1 PointOnRelatedElement: (c) IFCPOINTORVERTEXPOINT widens IFCPOINTORVERTEXPOINT with IFC4X3-only types"
    ],
    "IFCCONNECTIONSURFACEGEOMETRY": [
      "0 SurfaceOnRelatingElement: (c) IFCSURFACEORFACESURFACE widens IFCSURFACEORFACESURFACE with IFC4X3-only types",
      "1 SurfaceOnRelatedElement: (c) IFCSURFACEORFACESURFACE widens IFCSURFACEORFACESURFACE with IFC4X3-only types"
    ],
    "IFCCONNECTIONVOLUMEGEOMETRY": [
      "0 VolumeOnRelatingElement: (c) IFCSOLIDORSHELL widens IFCSOLIDORSHELL with IFC4X3-only types",
      "1 VolumeOnRelatedElement: (c) IFCSOLIDORSHELL widens IFCSOLIDORSHELL with IFC4X3-only types"
    ],
    "IFCCONSTRUCTIONEQUIPMENTRESOURCE": [
      "9 BaseQuantity: (c) IFCPHYSICALQUANTITY widens IFCPHYSICALQUANTITY with IFC4X3-only types"
    ],
    "IFCCONSTRUCTIONEQUIPMENTRESOURCETYPE": [
      "10 BaseQuantity: (c) IFCPHYSICALQUANTITY widens IFCPHYSICALQUANTITY with IFC4X3-only types"
    ],
    "IFCCONSTRUCTIONMATERIALRESOURCE": [
      "9 BaseQuantity: (c) IFCPHYSICALQUANTITY widens IFCPHYSICALQUANTITY with IFC4X3-only types"
    ],
    "IFCCONSTRUCTIONMATERIALRESOURCETYPE": [
      "10 BaseQuantity: (c) IFCPHYSICALQUANTITY widens IFCPHYSICALQUANTITY with IFC4X3-only types"
    ],
    "IFCCONSTRUCTIONPRODUCTRESOURCE": [
      "9 BaseQuantity: (c) IFCPHYSICALQUANTITY widens IFCPHYSICALQUANTITY with IFC4X3-only types"
    ],
    "IFCCONSTRUCTIONPRODUCTRESOURCETYPE": [
      "10 BaseQuantity: (c) IFCPHYSICALQUANTITY widens IFCPHYSICALQUANTITY with IFC4X3-only types"
    ],
    "IFCCONTROLLER": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCCOOLEDBEAM": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCCOOLINGTOWER": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCCOSTITEM": [
      "8 CostQuantities: (c) IFCPHYSICALQUANTITY widens IFCPHYSICALQUANTITY with IFC4X3-only types"
    ],
    "IFCCREWRESOURCE": [
      "9 BaseQuantity: (c) IFCPHYSICALQUANTITY widens IFCPHYSICALQUANTITY with IFC4X3-only types"
    ],
    "IFCCREWRESOURCETYPE": [
      "10 BaseQuantity: (c) IFCPHYSICALQUANTITY widens IFCPHYSICALQUANTITY with IFC4X3-only types"
    ],
    "IFCCURTAINWALL": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCCURVEBOUNDEDPLANE": [
      "1 OuterBoundary: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types",
      "2 InnerBoundaries: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types"
    ],
    "IFCCURVEBOUNDEDSURFACE": [
      "0 BasisSurface: (c) IFCSURFACE widens IFCSURFACE with IFC4X3-only types"
    ],
    "IFCCURVESTYLEFONTANDSCALING": [
      "1 CurveFont: (d) renamed CurveStyleFont in ADD2"
    ],
    "IFCDAMPER": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCDERIVEDPROFILEDEF": [
      "2 ParentProfile: (c) IFCPROFILEDEF widens IFCPROFILEDEF with IFC4X3-only types"
    ],
    "IFCDISTRIBUTIONCHAMBERELEMENT": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCDISTRIBUTIONCONTROLELEMENT": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCDISTRIBUTIONELEMENT": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCDISTRIBUTIONFLOWELEMENT": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCDUCTFITTING": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCDUCTSEGMENT": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCDUCTSILENCER": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCEDGECURVE": [
      "2 EdgeGeometry: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types"
    ],
    "IFCELECTRICAPPLIANCE": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCELECTRICDISTRIBUTIONBOARD": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCELECTRICGENERATOR": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCELECTRICMOTOR": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCELECTRICTIMECONTROL": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCELEMENTQUANTITY": [
      "5 Quantities: (c) IFCPHYSICALQUANTITY widens IFCPHYSICALQUANTITY with IFC4X3-only types"
    ],
    "IFCENERGYCONVERSIONDEVICE": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCENGINE": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCEVAPORATIVECOOLER": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCEVAPORATOR": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCEXTERNALREFERENCERELATIONSHIP": [
      "3 RelatedResourceObjects: (c) IFCRESOURCEOBJECTSELECT widens IFCRESOURCEOBJECTSELECT; loud: IFCSHAPEASPECT"
    ],
    "IFCEXTERNALSPATIALELEMENT": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCEXTRUDEDAREASOLID": [
      "0 SweptArea: (c) IFCPROFILEDEF widens IFCPROFILEDEF with IFC4X3-only types"
    ],
    "IFCEXTRUDEDAREASOLIDTAPERED": [
      "0 SweptArea: (c) IFCPROFILEDEF widens IFCPROFILEDEF with IFC4X3-only types",
      "4 EndSweptArea: (c) IFCPROFILEDEF widens IFCPROFILEDEF with IFC4X3-only types"
    ],
    "IFCFACESURFACE": [
      "1 FaceSurface: (c) IFCSURFACE widens IFCSURFACE with IFC4X3-only types"
    ],
    "IFCFAN": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCFASTENER": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCFILLAREASTYLE": [
      "2 ModelorDraughting: (d) renamed ModelOrDraughting in ADD2"
    ],
    "IFCFILTER": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCFLOWCONTROLLER": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCFLOWFITTING": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCFLOWMETER": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCFLOWMOVINGDEVICE": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCFLOWSEGMENT": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCFLOWSTORAGEDEVICE": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCFLOWTERMINAL": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCFLOWTREATMENTDEVICE": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCFOOTING": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCFURNISHINGELEMENT": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCGEOMETRICCURVESET": [
      "0 Elements: (c) IFCGEOMETRICSETSELECT widens IFCGEOMETRICSETSELECT with IFC4X3-only types"
    ],
    "IFCGEOMETRICSET": [
      "0 Elements: (c) IFCGEOMETRICSETSELECT widens IFCGEOMETRICSETSELECT with IFC4X3-only types"
    ],
    "IFCGRID": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCGRIDAXIS": [
      "1 AxisCurve: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types"
    ],
    "IFCHALFSPACESOLID": [
      "0 BaseSurface: (c) IFCSURFACE widens IFCSURFACE with IFC4X3-only types"
    ],
    "IFCHUMIDIFIER": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCINDEXEDCOLOURMAP": [
      "0 MappedTo: (c) IFCTESSELLATEDFACESET widens IFCTESSELLATEDFACESET with IFC4X3-only types"
    ],
    "IFCINDEXEDTRIANGLETEXTUREMAP": [
      "1 MappedTo: (c) IFCTESSELLATEDFACESET widens IFCTESSELLATEDFACESET with IFC4X3-only types"
    ],
    "IFCINTERCEPTOR": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCINTERSECTIONCURVE": [
      "0 Curve3D: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types"
    ],
    "IFCIRREGULARTIMESERIESVALUE": [
      "1 ListValues: (c) IFCVALUE widens IFCVALUE; loud: IFCURIREFERENCE"
    ],
    "IFCJUNCTIONBOX": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCLABORRESOURCE": [
      "9 BaseQuantity: (c) IFCPHYSICALQUANTITY widens IFCPHYSICALQUANTITY with IFC4X3-only types"
    ],
    "IFCLABORRESOURCETYPE": [
      "10 BaseQuantity: (c) IFCPHYSICALQUANTITY widens IFCPHYSICALQUANTITY with IFC4X3-only types"
    ],
    "IFCLAMP": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCLIGHTFIXTURE": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCLOCALPLACEMENT": [
      "0 PlacementRelTo: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCMAPCONVERSION": [
      "0 SourceCRS: (c) IFCCOORDINATEREFERENCESYSTEMSELECT widens IFCCOORDINATEREFERENCESYSTEMSELECT with IFC4X3-only types",
      "1 TargetCRS: (c) IFCCOORDINATEREFERENCESYSTEM widens IFCCOORDINATEREFERENCESYSTEM with IFC4X3-only types"
    ],
    "IFCMATERIALPROFILE": [
      "3 Profile: (c) IFCPROFILEDEF widens IFCPROFILEDEF with IFC4X3-only types"
    ],
    "IFCMATERIALPROFILEWITHOFFSETS": [
      "3 Profile: (c) IFCPROFILEDEF widens IFCPROFILEDEF with IFC4X3-only types"
    ],
    "IFCMATERIALRELATIONSHIP": [
      "4 Expression: (d) renamed MaterialExpression in ADD2"
    ],
    "IFCMEASUREWITHUNIT": [
      "0 ValueComponent: (c) IFCVALUE widens IFCVALUE; loud: IFCURIREFERENCE"
    ],
    "IFCMEDICALDEVICE": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCMETRIC": [
      "9 DataValue: (c) IFCMETRICVALUESELECT widens IFCMETRICVALUESELECT; loud: IFCURIREFERENCE"
    ],
    "IFCMIRROREDPROFILEDEF": [
      "2 ParentProfile: (c) IFCPROFILEDEF widens IFCPROFILEDEF with IFC4X3-only types"
    ],
    "IFCMOTORCONNECTION": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCOFFSETCURVE2D": [
      "0 BasisCurve: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types"
    ],
    "IFCOFFSETCURVE3D": [
      "0 BasisCurve: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types"
    ],
    "IFCOPENINGELEMENT": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCOUTERBOUNDARYCURVE": [
      "0 Segments: (c) IFCSEGMENT widens IFCCOMPOSITECURVESEGMENT with IFC4X3-only types"
    ],
    "IFCOUTLET": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCPCURVE": [
      "0 BasisSurface: (c) IFCSURFACE widens IFCSURFACE with IFC4X3-only types",
      "1 ReferenceCurve: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types"
    ],
    "IFCPHYSICALCOMPLEXQUANTITY": [
      "2 HasQuantities: (c) IFCPHYSICALQUANTITY widens IFCPHYSICALQUANTITY with IFC4X3-only types"
    ],
    "IFCPILE": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCPIPEFITTING": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCPIPESEGMENT": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCPOINTONCURVE": [
      "0 BasisCurve: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types"
    ],
    "IFCPOINTONSURFACE": [
      "0 BasisSurface: (c) IFCSURFACE widens IFCSURFACE with IFC4X3-only types"
    ],
    "IFCPOLYGONALBOUNDEDHALFSPACE": [
      "0 BaseSurface: (c) IFCSURFACE widens IFCSURFACE with IFC4X3-only types",
      "3 PolygonalBoundary: (c) IFCBOUNDEDCURVE widens IFCBOUNDEDCURVE with IFC4X3-only types"
    ],
    "IFCPRESENTATIONLAYERASSIGNMENT": [
      "2 AssignedItems: (c) IFCLAYEREDITEM widens IFCLAYEREDITEM with IFC4X3-only types"
    ],
    "IFCPRESENTATIONLAYERWITHSTYLE": [
      "2 AssignedItems: (c) IFCLAYEREDITEM widens IFCLAYEREDITEM with IFC4X3-only types"
    ],
    "IFCPROFILEPROPERTIES": [
      "3 ProfileDefinition: (c) IFCPROFILEDEF widens IFCPROFILEDEF with IFC4X3-only types"
    ],
    "IFCPROPERTYBOUNDEDVALUE": [
      "1 Description: (d) renamed Specification in ADD2",
      "2 UpperBoundValue: (c) IFCVALUE widens IFCVALUE; loud: IFCURIREFERENCE",
      "3 LowerBoundValue: (c) IFCVALUE widens IFCVALUE; loud: IFCURIREFERENCE",
      "5 SetPointValue: (c) IFCVALUE widens IFCVALUE; loud: IFCURIREFERENCE"
    ],
    "IFCPROPERTYENUMERATEDVALUE": [
      "1 Description: (d) renamed Specification in ADD2",
      "2 EnumerationValues: (c) IFCVALUE widens IFCVALUE; loud: IFCURIREFERENCE"
    ],
    "IFCPROPERTYENUMERATION": [
      "1 EnumerationValues: (c) IFCVALUE widens IFCVALUE; loud: IFCURIREFERENCE"
    ],
    "IFCPROPERTYLISTVALUE": [
      "1 Description: (d) renamed Specification in ADD2",
      "2 ListValues: (c) IFCVALUE widens IFCVALUE; loud: IFCURIREFERENCE"
    ],
    "IFCPROPERTYREFERENCEVALUE": [
      "1 Description: (d) renamed Specification in ADD2"
    ],
    "IFCPROPERTYSINGLEVALUE": [
      "1 Description: (d) renamed Specification in ADD2",
      "2 NominalValue: (c) IFCVALUE widens IFCVALUE; loud: IFCURIREFERENCE"
    ],
    "IFCPROPERTYTABLEVALUE": [
      "1 Description: (d) renamed Specification in ADD2",
      "2 DefiningValues: (c) IFCVALUE widens IFCVALUE; loud: IFCURIREFERENCE",
      "3 DefinedValues: (c) IFCVALUE widens IFCVALUE; loud: IFCURIREFERENCE"
    ],
    "IFCPROTECTIVEDEVICETRIPPINGUNIT": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCPUMP": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCRAMP": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCRAMPFLIGHT": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCRECTANGULARTRIMMEDSURFACE": [
      "0 BasisSurface: (c) IFCSURFACE widens IFCSURFACE with IFC4X3-only types"
    ],
    "IFCREINFORCINGMESH": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCRELAGGREGATES": [
      "4 RelatingObject: (c) IFCOBJECTDEFINITION widens IFCOBJECTDEFINITION with IFC4X3-only types",
      "5 RelatedObjects: (c) IFCOBJECTDEFINITION widens IFCOBJECTDEFINITION with IFC4X3-only types"
    ],
    "IFCRELASSOCIATESAPPROVAL": [
      "4 RelatedObjects: (c) IFCDEFINITIONSELECT widens IFCDEFINITIONSELECT with IFC4X3-only types"
    ],
    "IFCRELASSOCIATESCLASSIFICATION": [
      "4 RelatedObjects: (c) IFCDEFINITIONSELECT widens IFCDEFINITIONSELECT with IFC4X3-only types"
    ],
    "IFCRELASSOCIATESCONSTRAINT": [
      "4 RelatedObjects: (c) IFCDEFINITIONSELECT widens IFCDEFINITIONSELECT with IFC4X3-only types"
    ],
    "IFCRELASSOCIATESDOCUMENT": [
      "4 RelatedObjects: (c) IFCDEFINITIONSELECT widens IFCDEFINITIONSELECT with IFC4X3-only types"
    ],
    "IFCRELASSOCIATESLIBRARY": [
      "4 RelatedObjects: (c) IFCDEFINITIONSELECT widens IFCDEFINITIONSELECT with IFC4X3-only types"
    ],
    "IFCRELASSOCIATESMATERIAL": [
      "4 RelatedObjects: (c) IFCDEFINITIONSELECT widens IFCDEFINITIONSELECT with IFC4X3-only types"
    ],
    "IFCRELCONNECTSELEMENTS": [
      "5 RelatingElement: (c) IFCELEMENT widens IFCELEMENT with IFC4X3-only types",
      "6 RelatedElement: (c) IFCELEMENT widens IFCELEMENT with IFC4X3-only types"
    ],
    "IFCRELCONNECTSPATHELEMENTS": [
      "5 RelatingElement: (c) IFCELEMENT widens IFCELEMENT with IFC4X3-only types",
      "6 RelatedElement: (c) IFCELEMENT widens IFCELEMENT with IFC4X3-only types"
    ],
    "IFCRELCONNECTSPORTS": [
      "6 RealizingElement: (c) IFCELEMENT widens IFCELEMENT with IFC4X3-only types"
    ],
    "IFCRELCONNECTSPORTTOELEMENT": [
      "5 RelatedElement: (c) IFCDISTRIBUTIONELEMENT widens IFCDISTRIBUTIONELEMENT with IFC4X3-only types"
    ],
    "IFCRELCONNECTSSTRUCTURALACTIVITY": [
      "4 RelatingElement: (c) IFCSTRUCTURALACTIVITYASSIGNMENTSELECT widens IFCSTRUCTURALACTIVITYASSIGNMENTSELECT with IFC4X3-only types"
    ],
    "IFCRELCONNECTSWITHREALIZINGELEMENTS": [
      "5 RelatingElement: (c) IFCELEMENT widens IFCELEMENT with IFC4X3-only types",
      "6 RelatedElement: (c) IFCELEMENT widens IFCELEMENT with IFC4X3-only types",
      "7 RealizingElements: (c) IFCELEMENT widens IFCELEMENT with IFC4X3-only types"
    ],
    "IFCRELCONTAINEDINSPATIALSTRUCTURE": [
      "4 RelatedElements: (c) IFCPRODUCT widens IFCPRODUCT with IFC4X3-only types",
      "5 RelatingStructure: (c) IFCSPATIALELEMENT widens IFCSPATIALELEMENT with IFC4X3-only types"
    ],
    "IFCRELCOVERSBLDGELEMENTS": [
      "4 RelatingBuildingElement: (c) IFCELEMENT widens IFCELEMENT with IFC4X3-only types"
    ],
    "IFCRELDECLARES": [
      "5 RelatedDefinitions: (c) IFCDEFINITIONSELECT widens IFCDEFINITIONSELECT with IFC4X3-only types"
    ],
    "IFCRELDEFINESBYOBJECT": [
      "4 RelatedObjects: (c) IFCOBJECT widens IFCOBJECT with IFC4X3-only types",
      "5 RelatingObject: (c) IFCOBJECT widens IFCOBJECT with IFC4X3-only types"
    ],
    "IFCRELDEFINESBYPROPERTIES": [
      "4 RelatedObjects: (c) IFCOBJECTDEFINITION widens IFCOBJECTDEFINITION with IFC4X3-only types"
    ],
    "IFCRELDEFINESBYTYPE": [
      "4 RelatedObjects: (c) IFCOBJECT widens IFCOBJECT with IFC4X3-only types",
      "5 RelatingType: (c) IFCTYPEOBJECT widens IFCTYPEOBJECT with IFC4X3-only types"
    ],
    "IFCRELFILLSELEMENT": [
      "4 RelatingOpeningElement: (b) IFCOPENINGELEMENT domain superset of IFCOPENINGELEMENT",
      "5 RelatedBuildingElement: (c) IFCELEMENT widens IFCELEMENT with IFC4X3-only types"
    ],
    "IFCRELFLOWCONTROLELEMENTS": [
      "5 RelatingFlowElement: (c) IFCDISTRIBUTIONFLOWELEMENT widens IFCDISTRIBUTIONFLOWELEMENT with IFC4X3-only types"
    ],
    "IFCRELNESTS": [
      "4 RelatingObject: (c) IFCOBJECTDEFINITION widens IFCOBJECTDEFINITION with IFC4X3-only types",
      "5 RelatedObjects: (c) IFCOBJECTDEFINITION widens IFCOBJECTDEFINITION with IFC4X3-only types"
    ],
    "IFCRELPROJECTSELEMENT": [
      "4 RelatingElement: (c) IFCELEMENT widens IFCELEMENT with IFC4X3-only types"
    ],
    "IFCRELREFERENCEDINSPATIALSTRUCTURE": [
      "4 RelatedElements: (c) IFCSPATIALREFERENCESELECT widens IFCPRODUCT; loud: IFCASSET,IFCBUILDINGSYSTEM,IFCDISTRIBUTIONCIRCUIT,IFCDISTRIBUTIONSYSTEM,IFCGROUP,IFCINVENTORY,IFCSTRUCTURALANALYSISMODEL,IFCSTRUCTURALLOADCASE,IFCSTRUCTURALLOADGROUP,IFCSTRUCTURALRESULTGROUP,IFCSYSTEM,IFCZONE",
      "5 RelatingStructure: (c) IFCSPATIALELEMENT widens IFCSPATIALELEMENT with IFC4X3-only types"
    ],
    "IFCRELSERVICESBUILDINGS": [
      "4 RelatingSystem: (c) IFCSYSTEM widens IFCSYSTEM with IFC4X3-only types",
      "5 RelatedBuildings: (c) IFCSPATIALELEMENT widens IFCSPATIALELEMENT with IFC4X3-only types"
    ],
    "IFCRELSPACEBOUNDARY": [
      "5 RelatedBuildingElement: (c) IFCELEMENT widens IFCELEMENT with IFC4X3-only types"
    ],
    "IFCRELSPACEBOUNDARY1STLEVEL": [
      "5 RelatedBuildingElement: (c) IFCELEMENT widens IFCELEMENT with IFC4X3-only types"
    ],
    "IFCRELSPACEBOUNDARY2NDLEVEL": [
      "5 RelatedBuildingElement: (c) IFCELEMENT widens IFCELEMENT with IFC4X3-only types"
    ],
    "IFCRELVOIDSELEMENT": [
      "4 RelatingBuildingElement: (c) IFCELEMENT widens IFCELEMENT with IFC4X3-only types",
      "5 RelatedOpeningElement: (c) IFCFEATUREELEMENTSUBTRACTION widens IFCFEATUREELEMENTSUBTRACTION with IFC4X3-only types"
    ],
    "IFCREPARAMETRISEDCOMPOSITECURVESEGMENT": [
      "2 ParentCurve: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types"
    ],
    "IFCRESOURCEAPPROVALRELATIONSHIP": [
      "2 RelatedResourceObjects: (c) IFCRESOURCEOBJECTSELECT widens IFCRESOURCEOBJECTSELECT; loud: IFCSHAPEASPECT"
    ],
    "IFCRESOURCECONSTRAINTRELATIONSHIP": [
      "3 RelatedResourceObjects: (c) IFCRESOURCEOBJECTSELECT widens IFCRESOURCEOBJECTSELECT; loud: IFCSHAPEASPECT"
    ],
    "IFCREVOLVEDAREASOLID": [
      "0 SweptArea: (c) IFCPROFILEDEF widens IFCPROFILEDEF with IFC4X3-only types"
    ],
    "IFCREVOLVEDAREASOLIDTAPERED": [
      "0 SweptArea: (c) IFCPROFILEDEF widens IFCPROFILEDEF with IFC4X3-only types",
      "4 EndSweptArea: (c) IFCPROFILEDEF widens IFCPROFILEDEF with IFC4X3-only types"
    ],
    "IFCROOF": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSANITARYTERMINAL": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSEAMCURVE": [
      "0 Curve3D: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types"
    ],
    "IFCSECTIONEDSPINE": [
      "0 SpineCurve: (c) IFCCOMPOSITECURVE widens IFCCOMPOSITECURVE with IFC4X3-only types",
      "1 CrossSections: (c) IFCPROFILEDEF widens IFCPROFILEDEF with IFC4X3-only types"
    ],
    "IFCSECTIONPROPERTIES": [
      "1 StartProfile: (c) IFCPROFILEDEF widens IFCPROFILEDEF with IFC4X3-only types",
      "2 EndProfile: (c) IFCPROFILEDEF widens IFCPROFILEDEF with IFC4X3-only types"
    ],
    "IFCSHADINGDEVICE": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSHAPEREPRESENTATION": [
      "3 Items: (c) IFCREPRESENTATIONITEM widens IFCREPRESENTATIONITEM with IFC4X3-only types"
    ],
    "IFCSITE": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSOLARDEVICE": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSPACEHEATER": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSTACKTERMINAL": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSTAIRFLIGHT": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSTRUCTURALANALYSISMODEL": [
      "9 SharedPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSTRUCTURALCURVEACTION": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSTRUCTURALCURVECONNECTION": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types",
      "8 Axis: (d) renamed AxisDirection in ADD2"
    ],
    "IFCSTRUCTURALCURVEMEMBER": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSTRUCTURALCURVEMEMBERVARYING": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSTRUCTURALCURVEREACTION": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSTRUCTURALLINEARACTION": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSTRUCTURALPLANARACTION": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSTRUCTURALPOINTACTION": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSTRUCTURALPOINTCONNECTION": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSTRUCTURALPOINTREACTION": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSTRUCTURALSURFACEACTION": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSTRUCTURALSURFACECONNECTION": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSTRUCTURALSURFACEMEMBER": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSTRUCTURALSURFACEMEMBERVARYING": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSTRUCTURALSURFACEREACTION": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCSTYLEDITEM": [
      "0 Item: (c) IFCREPRESENTATIONITEM widens IFCREPRESENTATIONITEM with IFC4X3-only types",
      "1 Styles: (b) IFCSTYLEASSIGNMENTSELECT domain superset of IFCPRESENTATIONSTYLE"
    ],
    "IFCSTYLEDREPRESENTATION": [
      "3 Items: (c) IFCREPRESENTATIONITEM widens IFCREPRESENTATIONITEM with IFC4X3-only types"
    ],
    "IFCSUBCONTRACTRESOURCE": [
      "9 BaseQuantity: (c) IFCPHYSICALQUANTITY widens IFCPHYSICALQUANTITY with IFC4X3-only types"
    ],
    "IFCSUBCONTRACTRESOURCETYPE": [
      "10 BaseQuantity: (c) IFCPHYSICALQUANTITY widens IFCPHYSICALQUANTITY with IFC4X3-only types"
    ],
    "IFCSURFACECURVE": [
      "0 Curve3D: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types"
    ],
    "IFCSURFACEOFLINEAREXTRUSION": [
      "0 SweptCurve: (c) IFCPROFILEDEF widens IFCPROFILEDEF with IFC4X3-only types"
    ],
    "IFCSURFACEOFREVOLUTION": [
      "0 SweptCurve: (c) IFCPROFILEDEF widens IFCPROFILEDEF with IFC4X3-only types"
    ],
    "IFCSWEPTDISKSOLID": [
      "0 Directrix: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types"
    ],
    "IFCSWEPTDISKSOLIDPOLYGONAL": [
      "0 Directrix: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types"
    ],
    "IFCTABLEROW": [
      "0 RowCells: (c) IFCVALUE widens IFCVALUE; loud: IFCURIREFERENCE"
    ],
    "IFCTENDON": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCTENDONANCHOR": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCTIMESERIESVALUE": [
      "0 ListValues: (c) IFCVALUE widens IFCVALUE; loud: IFCURIREFERENCE"
    ],
    "IFCTOPOLOGYREPRESENTATION": [
      "3 Items: (c) IFCREPRESENTATIONITEM widens IFCREPRESENTATIONITEM with IFC4X3-only types"
    ],
    "IFCTRIMMEDCURVE": [
      "0 BasisCurve: (c) IFCCURVE widens IFCCURVE with IFC4X3-only types"
    ],
    "IFCTUBEBUNDLE": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCUNITARYEQUIPMENT": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCVALVE": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCVERTEXPOINT": [
      "0 VertexGeometry: (c) IFCPOINT widens IFCPOINT with IFC4X3-only types"
    ],
    "IFCVOIDINGFEATURE": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCWASTETERMINAL": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCWINDOW": [
      "5 ObjectPlacement: (c) IFCOBJECTPLACEMENT widens IFCOBJECTPLACEMENT with IFC4X3-only types"
    ],
    "IFCWORKTIME": [
      "4 Start: (d) renamed StartDate in ADD2",
      "5 Finish: (d) renamed FinishDate in ADD2"
    ]
  },
  "incompatible": {
    "IFCADDRESS": "abstract in IFC4",
    "IFCALARM": "8 PredefinedType: enum IFCALARMTYPEENUM values RAILWAYCROCODILE,RAILWAYDETONATOR not in IFC4 IFCALARMTYPEENUM",
    "IFCALARMTYPE": "9 PredefinedType: enum IFCALARMTYPEENUM values RAILWAYCROCODILE,RAILWAYDETONATOR not in IFC4 IFCALARMTYPEENUM",
    "IFCANNOTATION": "explicit attribute count 7 vs 8",
    "IFCAPPLIEDVALUE": "8 ArithmeticOperator: enum IFCARITHMETICOPERATORENUM values MODULO not in IFC4 IFCARITHMETICOPERATORENUM",
    "IFCAUDIOVISUALAPPLIANCE": "8 PredefinedType: enum IFCAUDIOVISUALAPPLIANCETYPEENUM values COMMUNICATIONTERMINAL,RECORDINGEQUIPMENT not in IFC4 IFCAUDIOVISUALAPPLIANCETYPEENUM",
    "IFCAUDIOVISUALAPPLIANCETYPE": "9 PredefinedType: enum IFCAUDIOVISUALAPPLIANCETYPEENUM values COMMUNICATIONTERMINAL,RECORDINGEQUIPMENT not in IFC4 IFCAUDIOVISUALAPPLIANCETYPEENUM",
    "IFCBEAM": "8 PredefinedType: enum IFCBEAMTYPEENUM values CORNICE,DIAPHRAGM,EDGEBEAM,GIRDER_SEGMENT,HATSTONE,PIERCAP not in IFC4 IFCBEAMTYPEENUM",
    "IFCBEAMTYPE": "9 PredefinedType: enum IFCBEAMTYPEENUM values CORNICE,DIAPHRAGM,EDGEBEAM,GIRDER_SEGMENT,HATSTONE,PIERCAP not in IFC4 IFCBEAMTYPEENUM",
    "IFCBOUNDARYCONDITION": "abstract in IFC4",
    "IFCBOUNDEDCURVE": "abstract in IFC4",
    "IFCBOUNDEDSURFACE": "abstract in IFC4",
    "IFCBSPLINECURVE": "abstract in IFC4",
    "IFCBSPLINESURFACE": "abstract in IFC4",
    "IFCBUILDINGELEMENTPART": "8 PredefinedType: enum IFCBUILDINGELEMENTPARTTYPEENUM values APRON,ARMOURUNIT,SAFETYCAGE not in IFC4 IFCBUILDINGELEMENTPARTTYPEENUM",
    "IFCBUILDINGELEMENTPARTTYPE": "9 PredefinedType: enum IFCBUILDINGELEMENTPARTTYPEENUM values APRON,ARMOURUNIT,SAFETYCAGE not in IFC4 IFCBUILDINGELEMENTPARTTYPEENUM",
    "IFCCABLECARRIERFITTING": "8 PredefinedType: enum IFCCABLECARRIERFITTINGTYPEENUM values CONNECTOR,JUNCTION,TRANSITION not in IFC4 IFCCABLECARRIERFITTINGTYPEENUM",
    "IFCCABLECARRIERFITTINGTYPE": "9 PredefinedType: enum IFCCABLECARRIERFITTINGTYPEENUM values CONNECTOR,JUNCTION,TRANSITION not in IFC4 IFCCABLECARRIERFITTINGTYPEENUM",
    "IFCCABLECARRIERSEGMENT": "8 PredefinedType: enum IFCCABLECARRIERSEGMENTTYPEENUM values CABLEBRACKET,CATENARYWIRE,DROPPER not in IFC4 IFCCABLECARRIERSEGMENTTYPEENUM",
    "IFCCABLECARRIERSEGMENTTYPE": "9 PredefinedType: enum IFCCABLECARRIERSEGMENTTYPEENUM values CABLEBRACKET,CATENARYWIRE,DROPPER not in IFC4 IFCCABLECARRIERSEGMENTTYPEENUM",
    "IFCCABLEFITTING": "8 PredefinedType: enum IFCCABLEFITTINGTYPEENUM values FANOUT not in IFC4 IFCCABLEFITTINGTYPEENUM",
    "IFCCABLEFITTINGTYPE": "9 PredefinedType: enum IFCCABLEFITTINGTYPEENUM values FANOUT not in IFC4 IFCCABLEFITTINGTYPEENUM",
    "IFCCABLESEGMENT": "8 PredefinedType: enum IFCCABLESEGMENTTYPEENUM values CONTACTWIRESEGMENT,FIBERSEGMENT,FIBERTUBE,OPTICALCABLESEGMENT,STITCHWIRE,WIREPAIRSEGMENT not in IFC4 IFCCABLESEGMENTTYPEENUM",
    "IFCCABLESEGMENTTYPE": "9 PredefinedType: enum IFCCABLESEGMENTTYPEENUM values CONTACTWIRESEGMENT,FIBERSEGMENT,FIBERTUBE,OPTICALCABLESEGMENT,STITCHWIRE,WIREPAIRSEGMENT not in IFC4 IFCCABLESEGMENTTYPEENUM",
    "IFCCARTESIANPOINTLIST": "abstract in IFC4",
    "IFCCARTESIANPOINTLIST2D": "explicit attribute count 1 vs 2",
    "IFCCARTESIANPOINTLIST3D": "explicit attribute count 1 vs 2",
    "IFCCARTESIANTRANSFORMATIONOPERATOR": "abstract in IFC4",
    "IFCCOLOURSPECIFICATION": "abstract in IFC4",
    "IFCCOLUMN": "8 PredefinedType: enum IFCCOLUMNTYPEENUM values PIERSTEM,PIERSTEM_SEGMENT,STANDCOLUMN not in IFC4 IFCCOLUMNTYPEENUM",
    "IFCCOLUMNTYPE": "9 PredefinedType: enum IFCCOLUMNTYPEENUM values PIERSTEM,PIERSTEM_SEGMENT,STANDCOLUMN not in IFC4 IFCCOLUMNTYPEENUM",
    "IFCCOMMUNICATIONSAPPLIANCE": "8 PredefinedType: enum IFCCOMMUNICATIONSAPPLIANCETYPEENUM values AUTOMATON,INTELLIGENTPERIPHERAL,IPNETWORKEQUIPMENT,LINESIDEELECTRONICUNIT,OPTICALLINETERMINAL,OPTICALNETWORKUNIT,RADIOBLOCKCENTER,TELECOMMAND,TELEPHONYEXCHANGE,TRANSITIONCOMPONENT,TRANSPONDER,TRANSPORTEQUIPMENT not in IFC4 IFCCOMMUNICATIONSAPPLIANCETYPEENUM",
    "IFCCOMMUNICATIONSAPPLIANCETYPE": "9 PredefinedType: enum IFCCOMMUNICATIONSAPPLIANCETYPEENUM values AUTOMATON,INTELLIGENTPERIPHERAL,IPNETWORKEQUIPMENT,LINESIDEELECTRONICUNIT,OPTICALLINETERMINAL,OPTICALNETWORKUNIT,RADIOBLOCKCENTER,TELECOMMAND,TELEPHONYEXCHANGE,TRANSITIONCOMPONENT,TRANSPONDER,TRANSPORTEQUIPMENT not in IFC4 IFCCOMMUNICATIONSAPPLIANCETYPEENUM",
    "IFCCONIC": "abstract in IFC4",
    "IFCCONNECTIONGEOMETRY": "abstract in IFC4",
    "IFCCONSTRAINT": "abstract in IFC4",
    "IFCCONSTRUCTIONRESOURCE": "abstract in IFC4",
    "IFCCONSTRUCTIONRESOURCETYPE": "abstract in IFC4",
    "IFCCONTEXT": "abstract in IFC4",
    "IFCCONTROL": "abstract in IFC4",
    "IFCCOORDINATEOPERATION": "abstract in IFC4",
    "IFCCOORDINATEREFERENCESYSTEM": "abstract in IFC4",
    "IFCCOSTVALUE": "8 ArithmeticOperator: enum IFCARITHMETICOPERATORENUM values MODULO not in IFC4 IFCARITHMETICOPERATORENUM",
    "IFCCOVERING": "8 PredefinedType: enum IFCCOVERINGTYPEENUM values COPING,TOPPING not in IFC4 IFCCOVERINGTYPEENUM",
    "IFCCOVERINGTYPE": "9 PredefinedType: enum IFCCOVERINGTYPEENUM values COPING,TOPPING not in IFC4 IFCCOVERINGTYPEENUM",
    "IFCCSGPRIMITIVE3D": "abstract in IFC4",
    "IFCCURVE": "abstract in IFC4",
    "IFCDERIVEDUNIT": "explicit attribute count 3 vs 4",
    "IFCDISCRETEACCESSORY": "8 PredefinedType: enum IFCDISCRETEACCESSORYTYPEENUM values BIRDPROTECTION,CABLEARRANGER,ELASTIC_CUSHION,EXPANSION_JOINT_DEVICE,FILLER,FLASHING,INSULATOR,LOCK,PANEL_STRENGTHENING,POINTMACHINEMOUNTINGDEVICE,POINT_MACHINE_LOCKING_DEVICE,RAILBRACE,RAILPAD,RAIL_LUBRICATION,RAIL_MECHANICAL_EQUIPMENT,SLIDINGCHAIR,SOUNDABSORPTION,TENSIONINGEQUIPMENT not in IFC4 IFCDISCRETEACCESSORYTYPEENUM",
    "IFCDISCRETEACCESSORYTYPE": "9 PredefinedType: enum IFCDISCRETEACCESSORYTYPEENUM values BIRDPROTECTION,CABLEARRANGER,ELASTIC_CUSHION,EXPANSION_JOINT_DEVICE,FILLER,FLASHING,INSULATOR,LOCK,PANEL_STRENGTHENING,POINTMACHINEMOUNTINGDEVICE,POINT_MACHINE_LOCKING_DEVICE,RAILBRACE,RAILPAD,RAIL_LUBRICATION,RAIL_MECHANICAL_EQUIPMENT,SLIDINGCHAIR,SOUNDABSORPTION,TENSIONINGEQUIPMENT not in IFC4 IFCDISCRETEACCESSORYTYPEENUM",
    "IFCDISTRIBUTIONCIRCUIT": "6 PredefinedType: enum IFCDISTRIBUTIONSYSTEMENUM values CATENARY_SYSTEM,FIXEDTRANSMISSIONNETWORK,MOBILENETWORK,MONITORINGSYSTEM,OPERATIONALTELEPHONYSYSTEM,OVERHEAD_CONTACTLINE_SYSTEM,RETURN_CIRCUIT not in IFC4 IFCDISTRIBUTIONSYSTEMENUM",
    "IFCDISTRIBUTIONCONTROLELEMENTTYPE": "abstract in IFC4",
    "IFCDISTRIBUTIONFLOWELEMENTTYPE": "abstract in IFC4",
    "IFCDISTRIBUTIONPORT": "8 PredefinedType: enum IFCDISTRIBUTIONPORTTYPEENUM values WIRELESS not in IFC4 IFCDISTRIBUTIONPORTTYPEENUM",
    "IFCDISTRIBUTIONSYSTEM": "6 PredefinedType: enum IFCDISTRIBUTIONSYSTEMENUM values CATENARY_SYSTEM,FIXEDTRANSMISSIONNETWORK,MOBILENETWORK,MONITORINGSYSTEM,OPERATIONALTELEPHONYSYSTEM,OVERHEAD_CONTACTLINE_SYSTEM,RETURN_CIRCUIT not in IFC4 IFCDISTRIBUTIONSYSTEMENUM",
    "IFCDOOR": "10 PredefinedType: enum IFCDOORTYPEENUM values BOOM_BARRIER,TURNSTILE not in IFC4 IFCDOORTYPEENUM",
    "IFCDOORTYPE": "9 PredefinedType: enum IFCDOORTYPEENUM values BOOM_BARRIER,TURNSTILE not in IFC4 IFCDOORTYPEENUM",
    "IFCELECTRICFLOWSTORAGEDEVICE": "8 PredefinedType: enum IFCELECTRICFLOWSTORAGEDEVICETYPEENUM values CAPACITOR,COMPENSATOR,INDUCTOR,RECHARGER not in IFC4 IFCELECTRICFLOWSTORAGEDEVICETYPEENUM",
    "IFCELECTRICFLOWSTORAGEDEVICETYPE": "9 PredefinedType: enum IFCELECTRICFLOWSTORAGEDEVICETYPEENUM values CAPACITOR,COMPENSATOR,INDUCTOR,RECHARGER not in IFC4 IFCELECTRICFLOWSTORAGEDEVICETYPEENUM",
    "IFCELEMENT": "abstract in IFC4",
    "IFCELEMENTARYSURFACE": "abstract in IFC4",
    "IFCELEMENTASSEMBLY": "9 PredefinedType: enum IFCELEMENTASSEMBLYTYPEENUM values ABUTMENT,CROSS_BRACING,DECK,DILATATIONPANEL,ENTRANCEWORKS,GRID,MAST,PIER,PYLON,RAIL_MECHANICAL_EQUIPMENT_ASSEMBLY,SHELTER,SIGNALASSEMBLY,SUMPBUSTER,SUPPORTINGASSEMBLY,SUSPENSIONASSEMBLY,TRACKPANEL,TRACTION_SWITCHING_ASSEMBLY,TRAFFIC_CALMING_DEVICE,TURNOUTPANEL not in IFC4 IFCELEMENTASSEMBLYTYPEENUM",
    "IFCELEMENTASSEMBLYTYPE": "9 PredefinedType: enum IFCELEMENTASSEMBLYTYPEENUM values ABUTMENT,CROSS_BRACING,DECK,DILATATIONPANEL,ENTRANCEWORKS,GRID,MAST,PIER,PYLON,RAIL_MECHANICAL_EQUIPMENT_ASSEMBLY,SHELTER,SIGNALASSEMBLY,SUMPBUSTER,SUPPORTINGASSEMBLY,SUSPENSIONASSEMBLY,TRACKPANEL,TRACTION_SWITCHING_ASSEMBLY,TRAFFIC_CALMING_DEVICE,TURNOUTPANEL not in IFC4 IFCELEMENTASSEMBLYTYPEENUM",
    "IFCELEMENTCOMPONENT": "abstract in IFC4",
    "IFCELEMENTCOMPONENTTYPE": "abstract in IFC4",
    "IFCELEMENTTYPE": "abstract in IFC4",
    "IFCENERGYCONVERSIONDEVICETYPE": "abstract in IFC4",
    "IFCEXTENDEDPROPERTIES": "abstract in IFC4",
    "IFCEXTERNALINFORMATION": "abstract in IFC4",
    "IFCEXTERNALREFERENCE": "abstract in IFC4",
    "IFCEXTERNALSPATIALSTRUCTUREELEMENT": "abstract in IFC4",
    "IFCFEATUREELEMENT": "abstract in IFC4",
    "IFCFEATUREELEMENTADDITION": "abstract in IFC4",
    "IFCFEATUREELEMENTSUBTRACTION": "abstract in IFC4",
    "IFCFIRESUPPRESSIONTERMINAL": "8 PredefinedType: enum IFCFIRESUPPRESSIONTERMINALTYPEENUM values FIREMONITOR not in IFC4 IFCFIRESUPPRESSIONTERMINALTYPEENUM",
    "IFCFIRESUPPRESSIONTERMINALTYPE": "9 PredefinedType: enum IFCFIRESUPPRESSIONTERMINALTYPEENUM values FIREMONITOR not in IFC4 IFCFIRESUPPRESSIONTERMINALTYPEENUM",
    "IFCFIXEDREFERENCESWEPTAREASOLID": "3 StartParam: value IFCPARAMETERVALUE(0:REAL) vs IFCCURVEMEASURESELECT(undefined)",
    "IFCFLOWCONTROLLERTYPE": "abstract in IFC4",
    "IFCFLOWFITTINGTYPE": "abstract in IFC4",
    "IFCFLOWINSTRUMENT": "8 PredefinedType: enum IFCFLOWINSTRUMENTTYPEENUM values COMBINED,VOLTMETER not in IFC4 IFCFLOWINSTRUMENTTYPEENUM",
    "IFCFLOWINSTRUMENTTYPE": "9 PredefinedType: enum IFCFLOWINSTRUMENTTYPEENUM values COMBINED,VOLTMETER not in IFC4 IFCFLOWINSTRUMENTTYPEENUM",
    "IFCFLOWMOVINGDEVICETYPE": "abstract in IFC4",
    "IFCFLOWSEGMENTTYPE": "abstract in IFC4",
    "IFCFLOWSTORAGEDEVICETYPE": "abstract in IFC4",
    "IFCFLOWTERMINALTYPE": "abstract in IFC4",
    "IFCFLOWTREATMENTDEVICETYPE": "abstract in IFC4",
    "IFCFURNITURE": "8 PredefinedType: enum IFCFURNITURETYPEENUM values TECHNICALCABINET not in IFC4 IFCFURNITURETYPEENUM",
    "IFCFURNITURETYPE": "10 PredefinedType: enum IFCFURNITURETYPEENUM values TECHNICALCABINET not in IFC4 IFCFURNITURETYPEENUM",
    "IFCGEOGRAPHICELEMENT": "8 PredefinedType: enum IFCGEOGRAPHICELEMENTTYPEENUM values SOIL_BORING_POINT,VEGETATION not in IFC4 IFCGEOGRAPHICELEMENTTYPEENUM",
    "IFCGEOGRAPHICELEMENTTYPE": "9 PredefinedType: enum IFCGEOGRAPHICELEMENTTYPEENUM values SOIL_BORING_POINT,VEGETATION not in IFC4 IFCGEOGRAPHICELEMENTTYPEENUM",
    "IFCGEOMETRICREPRESENTATIONITEM": "abstract in IFC4",
    "IFCGRIDPLACEMENT": "explicit attribute count 2 vs 3",
    "IFCHEATEXCHANGER": "8 PredefinedType: enum IFCHEATEXCHANGERTYPEENUM values TURNOUTHEATING not in IFC4 IFCHEATEXCHANGERTYPEENUM",
    "IFCHEATEXCHANGERTYPE": "9 PredefinedType: enum IFCHEATEXCHANGERTYPEENUM values TURNOUTHEATING not in IFC4 IFCHEATEXCHANGERTYPEENUM",
    "IFCINDEXEDTEXTUREMAP": "abstract in IFC4",
    "IFCLIGHTSOURCE": "abstract in IFC4",
    "IFCMANIFOLDSOLIDBREP": "abstract in IFC4",
    "IFCMATERIALDEFINITION": "abstract in IFC4",
    "IFCMATERIALUSAGEDEFINITION": "abstract in IFC4",
    "IFCMECHANICALFASTENER": "10 PredefinedType: enum IFCMECHANICALFASTENERTYPEENUM values CHAIN,COUPLER,RAILFASTENING,RAILJOINT,ROPE not in IFC4 IFCMECHANICALFASTENERTYPEENUM",
    "IFCMECHANICALFASTENERTYPE": "9 PredefinedType: enum IFCMECHANICALFASTENERTYPEENUM values CHAIN,COUPLER,RAILFASTENING,RAILJOINT,ROPE not in IFC4 IFCMECHANICALFASTENERTYPEENUM",
    "IFCMEMBER": "8 PredefinedType: enum IFCMEMBERTYPEENUM values ARCH_SEGMENT,STAY_CABLE,STIFFENING_RIB,STRUCTURALCABLE,SUSPENDER,SUSPENSION_CABLE,TIEBAR not in IFC4 IFCMEMBERTYPEENUM",
    "IFCMEMBERTYPE": "9 PredefinedType: enum IFCMEMBERTYPEENUM values ARCH_SEGMENT,STAY_CABLE,STIFFENING_RIB,STRUCTURALCABLE,SUSPENDER,SUSPENSION_CABLE,TIEBAR not in IFC4 IFCMEMBERTYPEENUM",
    "IFCNAMEDUNIT": "abstract in IFC4",
    "IFCOBJECT": "abstract in IFC4",
    "IFCOBJECTDEFINITION": "abstract in IFC4",
    "IFCOBJECTPLACEMENT": "abstract in IFC4",
    "IFCPARAMETERIZEDPROFILEDEF": "abstract in IFC4",
    "IFCPHYSICALQUANTITY": "abstract in IFC4",
    "IFCPHYSICALSIMPLEQUANTITY": "abstract in IFC4",
    "IFCPLACEMENT": "abstract in IFC4",
    "IFCPLATE": "8 PredefinedType: enum IFCPLATETYPEENUM values BASE_PLATE,COVER_PLATE,FLANGE_PLATE,GUSSET_PLATE,SPLICE_PLATE,STIFFENER_PLATE,WEB_PLATE not in IFC4 IFCPLATETYPEENUM",
    "IFCPLATETYPE": "9 PredefinedType: enum IFCPLATETYPEENUM values BASE_PLATE,COVER_PLATE,FLANGE_PLATE,GUSSET_PLATE,SPLICE_PLATE,STIFFENER_PLATE,WEB_PLATE not in IFC4 IFCPLATETYPEENUM",
    "IFCPOINT": "abstract in IFC4",
    "IFCPORT": "abstract in IFC4",
    "IFCPREDEFINEDCOLOUR": "abstract in IFC4",
    "IFCPREDEFINEDCURVEFONT": "abstract in IFC4",
    "IFCPREDEFINEDITEM": "abstract in IFC4",
    "IFCPREDEFINEDPROPERTIES": "abstract in IFC4",
    "IFCPREDEFINEDPROPERTYSET": "abstract in IFC4",
    "IFCPREDEFINEDTEXTFONT": "abstract in IFC4",
    "IFCPRESENTATIONITEM": "abstract in IFC4",
    "IFCPRESENTATIONSTYLE": "abstract in IFC4",
    "IFCPROCESS": "abstract in IFC4",
    "IFCPRODUCT": "abstract in IFC4",
    "IFCPRODUCTREPRESENTATION": "abstract in IFC4",
    "IFCPROJECTEDCRS": "0 Name: OPTIONAL in ADD2 but required in IFC4",
    "IFCPROJECTIONELEMENT": "8 PredefinedType: enum IFCPROJECTIONELEMENTTYPEENUM values BLISTER,DEVIATOR not in IFC4 IFCPROJECTIONELEMENTTYPEENUM",
    "IFCPROPERTY": "abstract in IFC4",
    "IFCPROPERTYABSTRACTION": "abstract in IFC4",
    "IFCPROPERTYDEFINITION": "abstract in IFC4",
    "IFCPROPERTYSETDEFINITION": "abstract in IFC4",
    "IFCPROPERTYSETTEMPLATE": "4 TemplateType: enum IFCPROPERTYSETTEMPLATETYPEENUM values PSET_MATERIALDRIVEN,PSET_PROFILEDRIVEN not in IFC4 IFCPROPERTYSETTEMPLATETYPEENUM",
    "IFCPROPERTYTEMPLATE": "abstract in IFC4",
    "IFCPROPERTYTEMPLATEDEFINITION": "abstract in IFC4",
    "IFCPROTECTIVEDEVICE": "8 PredefinedType: enum IFCPROTECTIVEDEVICETYPEENUM values ANTI_ARCING_DEVICE,SPARKGAP,VOLTAGELIMITER not in IFC4 IFCPROTECTIVEDEVICETYPEENUM",
    "IFCPROTECTIVEDEVICETYPE": "9 PredefinedType: enum IFCPROTECTIVEDEVICETYPEENUM values ANTI_ARCING_DEVICE,SPARKGAP,VOLTAGELIMITER not in IFC4 IFCPROTECTIVEDEVICETYPEENUM",
    "IFCQUANTITYCOUNT": "3 CountValue: value IFCCOUNTMEASURE(0:NUMBER) vs IFCCOUNTMEASURE(0:INTEGER)",
    "IFCQUANTITYSET": "abstract in IFC4",
    "IFCRAILING": "8 PredefinedType: enum IFCRAILINGTYPEENUM values FENCE not in IFC4 IFCRAILINGTYPEENUM",
    "IFCRAILINGTYPE": "9 PredefinedType: enum IFCRAILINGTYPEENUM values FENCE not in IFC4 IFCRAILINGTYPEENUM",
    "IFCREINFORCEMENTBARPROPERTIES": "5 BarCount: value IFCCOUNTMEASURE(0:NUMBER) vs IFCCOUNTMEASURE(0:INTEGER)",
    "IFCREINFORCINGBAR": "12 PredefinedType: enum IFCREINFORCINGBARTYPEENUM values SPACEBAR not in IFC4 IFCREINFORCINGBARTYPEENUM",
    "IFCREINFORCINGBARTYPE": "9 PredefinedType: enum IFCREINFORCINGBARTYPEENUM values SPACEBAR not in IFC4 IFCREINFORCINGBARTYPEENUM",
    "IFCREINFORCINGELEMENT": "abstract in IFC4",
    "IFCREINFORCINGELEMENTTYPE": "abstract in IFC4",
    "IFCRELASSIGNS": "abstract in IFC4",
    "IFCRELASSIGNSTOACTOR": "5 RelatedObjectsType: value IFCOBJECTTYPEENUM(undefined) vs IFCSTRIPPEDOPTIONAL(0:BOOLEAN)",
    "IFCRELASSIGNSTOCONTROL": "5 RelatedObjectsType: value IFCOBJECTTYPEENUM(undefined) vs IFCSTRIPPEDOPTIONAL(0:BOOLEAN)",
    "IFCRELASSIGNSTOGROUP": "5 RelatedObjectsType: value IFCOBJECTTYPEENUM(undefined) vs IFCSTRIPPEDOPTIONAL(0:BOOLEAN)",
    "IFCRELASSIGNSTOGROUPBYFACTOR": "5 RelatedObjectsType: value IFCOBJECTTYPEENUM(undefined) vs IFCSTRIPPEDOPTIONAL(0:BOOLEAN)",
    "IFCRELASSIGNSTOPROCESS": "5 RelatedObjectsType: value IFCOBJECTTYPEENUM(undefined) vs IFCSTRIPPEDOPTIONAL(0:BOOLEAN)",
    "IFCRELASSIGNSTOPRODUCT": "5 RelatedObjectsType: value IFCOBJECTTYPEENUM(undefined) vs IFCSTRIPPEDOPTIONAL(0:BOOLEAN)",
    "IFCRELASSIGNSTORESOURCE": "5 RelatedObjectsType: value IFCOBJECTTYPEENUM(undefined) vs IFCSTRIPPEDOPTIONAL(0:BOOLEAN)",
    "IFCRELASSOCIATES": "abstract in IFC4",
    "IFCRELATIONSHIP": "abstract in IFC4",
    "IFCRELCONNECTS": "abstract in IFC4",
    "IFCRELDECOMPOSES": "abstract in IFC4",
    "IFCRELDEFINES": "abstract in IFC4",
    "IFCRELINTERFERESELEMENTS": "explicit attribute count 9 vs 10",
    "IFCREPRESENTATION": "abstract in IFC4",
    "IFCREPRESENTATIONCONTEXT": "abstract in IFC4",
    "IFCREPRESENTATIONITEM": "abstract in IFC4",
    "IFCRESOURCE": "abstract in IFC4",
    "IFCRESOURCELEVELRELATIONSHIP": "abstract in IFC4",
    "IFCROOT": "abstract in IFC4",
    "IFCSCHEDULINGTIME": "abstract in IFC4",
    "IFCSENSOR": "8 PredefinedType: enum IFCSENSORTYPEENUM values EARTHQUAKESENSOR,FOREIGNOBJECTDETECTIONSENSOR,OBSTACLESENSOR,RAINSENSOR,SNOWDEPTHSENSOR,TRAINSENSOR,TURNOUTCLOSURESENSOR,WHEELSENSOR not in IFC4 IFCSENSORTYPEENUM",
    "IFCSENSORTYPE": "9 PredefinedType: enum IFCSENSORTYPEENUM values EARTHQUAKESENSOR,FOREIGNOBJECTDETECTIONSENSOR,OBSTACLESENSOR,RAINSENSOR,SNOWDEPTHSENSOR,TRAINSENSOR,TURNOUTCLOSURESENSOR,WHEELSENSOR not in IFC4 IFCSENSORTYPEENUM",
    "IFCSHAPEMODEL": "abstract in IFC4",
    "IFCSIMPLEPROPERTY": "abstract in IFC4",
    "IFCSIMPLEPROPERTYTEMPLATE": "4 TemplateType: enum IFCSIMPLEPROPERTYTEMPLATETYPEENUM values Q_NUMBER not in IFC4 IFCSIMPLEPROPERTYTEMPLATETYPEENUM",
    "IFCSLAB": "8 PredefinedType: enum IFCSLABTYPEENUM values APPROACH_SLAB,PAVING,SIDEWALK,TRACKSLAB,WEARING not in IFC4 IFCSLABTYPEENUM",
    "IFCSLABTYPE": "9 PredefinedType: enum IFCSLABTYPEENUM values APPROACH_SLAB,PAVING,SIDEWALK,TRACKSLAB,WEARING not in IFC4 IFCSLABTYPEENUM",
    "IFCSOLIDMODEL": "abstract in IFC4",
    "IFCSPACE": "9 PredefinedType: enum IFCSPACETYPEENUM values BERTH not in IFC4 IFCSPACETYPEENUM",
    "IFCSPACETYPE": "9 PredefinedType: enum IFCSPACETYPEENUM values BERTH not in IFC4 IFCSPACETYPEENUM",
    "IFCSPATIALELEMENT": "abstract in IFC4",
    "IFCSPATIALELEMENTTYPE": "abstract in IFC4",
    "IFCSPATIALSTRUCTUREELEMENT": "abstract in IFC4",
    "IFCSPATIALSTRUCTUREELEMENTTYPE": "abstract in IFC4",
    "IFCSPATIALZONE": "8 PredefinedType: enum IFCSPATIALZONETYPEENUM values INTERFERENCE,RESERVATION not in IFC4 IFCSPATIALZONETYPEENUM",
    "IFCSPATIALZONETYPE": "9 PredefinedType: enum IFCSPATIALZONETYPEENUM values INTERFERENCE,RESERVATION not in IFC4 IFCSPATIALZONETYPEENUM",
    "IFCSTAIR": "8 PredefinedType: enum IFCSTAIRTYPEENUM values LADDER not in IFC4 IFCSTAIRTYPEENUM",
    "IFCSTAIRTYPE": "9 PredefinedType: enum IFCSTAIRTYPEENUM values LADDER not in IFC4 IFCSTAIRTYPEENUM",
    "IFCSTRUCTURALACTION": "abstract in IFC4",
    "IFCSTRUCTURALACTIVITY": "abstract in IFC4",
    "IFCSTRUCTURALCONNECTION": "abstract in IFC4",
    "IFCSTRUCTURALCONNECTIONCONDITION": "abstract in IFC4",
    "IFCSTRUCTURALITEM": "abstract in IFC4",
    "IFCSTRUCTURALLOAD": "abstract in IFC4",
    "IFCSTRUCTURALLOADORRESULT": "abstract in IFC4",
    "IFCSTRUCTURALLOADSTATIC": "abstract in IFC4",
    "IFCSTRUCTURALMEMBER": "abstract in IFC4",
    "IFCSTRUCTURALREACTION": "abstract in IFC4",
    "IFCSTYLEMODEL": "abstract in IFC4",
    "IFCSURFACE": "abstract in IFC4",
    "IFCSURFACECURVESWEPTAREASOLID": "3 StartParam: value IFCPARAMETERVALUE(0:REAL) vs IFCCURVEMEASURESELECT(undefined)",
    "IFCSURFACEFEATURE": "8 PredefinedType: enum IFCSURFACEFEATURETYPEENUM values DEFECT,HATCHMARKING,LINEMARKING,NONSKIDSURFACING,PAVEMENTSURFACEMARKING,RUMBLESTRIP,SYMBOLMARKING,TRANSVERSERUMBLESTRIP not in IFC4 IFCSURFACEFEATURETYPEENUM",
    "IFCSURFACESTYLERENDERING": "8 ReflectanceMethod: enum IFCREFLECTANCEMETHODENUM values PHYSICAL not in IFC4 IFCREFLECTANCEMETHODENUM",
    "IFCSURFACETEXTURE": "abstract in IFC4",
    "IFCSWEPTAREASOLID": "abstract in IFC4",
    "IFCSWEPTSURFACE": "abstract in IFC4",
    "IFCSWITCHINGDEVICE": "8 PredefinedType: enum IFCSWITCHINGDEVICETYPEENUM values RELAY,START_AND_STOP_EQUIPMENT not in IFC4 IFCSWITCHINGDEVICETYPEENUM",
    "IFCSWITCHINGDEVICETYPE": "9 PredefinedType: enum IFCSWITCHINGDEVICETYPEENUM values RELAY,START_AND_STOP_EQUIPMENT not in IFC4 IFCSWITCHINGDEVICETYPEENUM",
    "IFCSYSTEMFURNITUREELEMENT": "8 PredefinedType: enum IFCSYSTEMFURNITUREELEMENTTYPEENUM values SUBRACK not in IFC4 IFCSYSTEMFURNITUREELEMENTTYPEENUM",
    "IFCSYSTEMFURNITUREELEMENTTYPE": "9 PredefinedType: enum IFCSYSTEMFURNITUREELEMENTTYPEENUM values SUBRACK not in IFC4 IFCSYSTEMFURNITUREELEMENTTYPEENUM",
    "IFCTANK": "8 PredefinedType: enum IFCTANKTYPEENUM values OILRETENTIONTRAY not in IFC4 IFCTANKTYPEENUM",
    "IFCTANKTYPE": "9 PredefinedType: enum IFCTANKTYPEENUM values OILRETENTIONTRAY not in IFC4 IFCTANKTYPEENUM",
    "IFCTASK": "12 PredefinedType: enum IFCTASKTYPEENUM values ADJUSTMENT,CALIBRATION,EMERGENCY,INSPECTION,SAFETY,SHUTDOWN,STARTUP,TESTING,TROUBLESHOOTING not in IFC4 IFCTASKTYPEENUM",
    "IFCTASKTYPE": "9 PredefinedType: enum IFCTASKTYPEENUM values ADJUSTMENT,CALIBRATION,EMERGENCY,INSPECTION,SAFETY,SHUTDOWN,STARTUP,TESTING,TROUBLESHOOTING not in IFC4 IFCTASKTYPEENUM",
    "IFCTESSELLATEDFACESET": "abstract in IFC4",
    "IFCTESSELLATEDITEM": "abstract in IFC4",
    "IFCTEXTURECOORDINATE": "abstract in IFC4",
    "IFCTIMESERIES": "abstract in IFC4",
    "IFCTOPOLOGICALREPRESENTATIONITEM": "abstract in IFC4",
    "IFCTRANSFORMER": "8 PredefinedType: enum IFCTRANSFORMERTYPEENUM values CHOPPER,COMBINED not in IFC4 IFCTRANSFORMERTYPEENUM",
    "IFCTRANSFORMERTYPE": "9 PredefinedType: enum IFCTRANSFORMERTYPEENUM values CHOPPER,COMBINED not in IFC4 IFCTRANSFORMERTYPEENUM",
    "IFCTRANSPORTELEMENT": "8 PredefinedType: enum IFCTRANSPORTELEMENTTYPEENUM values HAULINGGEAR not in IFC4 IFCTRANSPORTELEMENTTYPEENUM",
    "IFCTRANSPORTELEMENTTYPE": "9 PredefinedType: enum IFCTRANSPORTELEMENTTYPEENUM values HAULINGGEAR not in IFC4 IFCTRANSPORTELEMENTTYPEENUM",
    "IFCTYPEPROCESS": "abstract in IFC4",
    "IFCTYPERESOURCE": "abstract in IFC4",
    "IFCUNITARYCONTROLELEMENT": "8 PredefinedType: enum IFCUNITARYCONTROLELEMENTTYPEENUM values BASESTATIONCONTROLLER,COMBINED not in IFC4 IFCUNITARYCONTROLELEMENTTYPEENUM",
    "IFCUNITARYCONTROLELEMENTTYPE": "9 PredefinedType: enum IFCUNITARYCONTROLELEMENTTYPEENUM values BASESTATIONCONTROLLER,COMBINED not in IFC4 IFCUNITARYCONTROLELEMENTTYPEENUM",
    "IFCVIBRATIONISOLATOR": "8 PredefinedType: enum IFCVIBRATIONISOLATORTYPEENUM values BASE not in IFC4 IFCVIBRATIONISOLATORTYPEENUM",
    "IFCVIBRATIONISOLATORTYPE": "9 PredefinedType: enum IFCVIBRATIONISOLATORTYPEENUM values BASE not in IFC4 IFCVIBRATIONISOLATORTYPEENUM",
    "IFCVIRTUALELEMENT": "explicit attribute count 8 vs 9",
    "IFCWALL": "8 PredefinedType: enum IFCWALLTYPEENUM values RETAININGWALL,WAVEWALL not in IFC4 IFCWALLTYPEENUM",
    "IFCWALLSTANDARDCASE": "8 PredefinedType: enum IFCWALLTYPEENUM values RETAININGWALL,WAVEWALL not in IFC4 IFCWALLTYPEENUM",
    "IFCWALLTYPE": "9 PredefinedType: enum IFCWALLTYPEENUM values RETAININGWALL,WAVEWALL not in IFC4 IFCWALLTYPEENUM",
    "IFCWORKCONTROL": "abstract in IFC4",
    "IFCCOUNTMEASURE": "value shape 0:NUMBER vs 0:INTEGER",
    "IFCPROPERTYSETDEFINITIONSET": "value shape undefined vs undefined"
  },
  "translationChecks": {
    "IFCROAD": [],
    "IFCFACILITYPART": [],
    "IFCPAVEMENT": [],
    "IFCKERB": []
  }
}

export default DECODE_COMPAT
